//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace WcfService
{
    public partial class WCFDataEntities : ObjectContext
    {
        public const string ConnectionString = "name=WCFDataEntities";
        public const string ContainerName = "WCFDataEntities";
    
        #region Constructors
    
        public WCFDataEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public WCFDataEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public WCFDataEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<ComputerBuildReport> ComputerBuildReports
        {
            get { return _computerBuildReports  ?? (_computerBuildReports = CreateObjectSet<ComputerBuildReport>("ComputerBuildReports")); }
        }
        private ObjectSet<ComputerBuildReport> _computerBuildReports;
    
        public ObjectSet<HardwareBindingReport> HardwareBindingReports
        {
            get { return _hardwareBindingReports  ?? (_hardwareBindingReports = CreateObjectSet<HardwareBindingReport>("HardwareBindingReports")); }
        }
        private ObjectSet<HardwareBindingReport> _hardwareBindingReports;
    
        public ObjectSet<ProductKeyInfo> ProductKeyInfoes
        {
            get { return _productKeyInfoes  ?? (_productKeyInfoes = CreateObjectSet<ProductKeyInfo>("ProductKeyInfoes")); }
        }
        private ObjectSet<ProductKeyInfo> _productKeyInfoes;
    
        public ObjectSet<ReturnReport> ReturnReports
        {
            get { return _returnReports  ?? (_returnReports = CreateObjectSet<ReturnReport>("ReturnReports")); }
        }
        private ObjectSet<ReturnReport> _returnReports;
    
        public ObjectSet<ReturnReportKey> ReturnReportKeys
        {
            get { return _returnReportKeys  ?? (_returnReportKeys = CreateObjectSet<ReturnReportKey>("ReturnReportKeys")); }
        }
        private ObjectSet<ReturnReportKey> _returnReportKeys;

        #endregion

    }
}
