//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WcfService
{
    public partial class ProductKeyInfo
    {
        #region Primitive Properties
    
        public virtual long ProductKeyID
        {
            get;
            set;
        }
    
        public virtual string ProductKey
        {
            get;
            set;
        }
    
        public virtual string HardwareID
        {
            get;
            set;
        }
    
        public virtual string EndItemPartNumber
        {
            get;
            set;
        }
    
        public virtual string OEMPartNumber
        {
            get;
            set;
        }
    
        public virtual string OEMAdditionalInfo
        {
            get;
            set;
        }
    
        public virtual string SoldToCustomerName
        {
            get;
            set;
        }
    
        public virtual Nullable<System.Guid> OrderUniqueID
        {
            get;
            set;
        }
    
        public virtual string SoldToCustomerID
        {
            get;
            set;
        }
    
        public virtual string CallOffReferenceNumber
        {
            get;
            set;
        }
    
        public virtual string OEMPONumber
        {
            get;
            set;
        }
    
        public virtual Nullable<int> OEMPOLineNumber
        {
            get;
            set;
        }
    
        public virtual string MSOrderNumber
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MSOrderLineNumber
        {
            get;
            set;
        }
    
        public virtual string LicensablePartNumber
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Quantity
        {
            get;
            set;
        }
    
        public virtual string ProductKeyState
        {
            get;
            set;
        }
    
        public virtual string SKUID
        {
            get;
            set;
        }
    
        public virtual string ReturnReasonCode
        {
            get;
            set;
        }
    
        public virtual string ActionCode
        {
            get;
            set;
        }
    
        public virtual string CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreatedDate
        {
            get;
            set;
        }
    
        public virtual string ModifiedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> FulfillmentResendIndicator
        {
            get;
            set;
        }
    
        public virtual string FulfillmentNumber
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FulfilledDateUTC
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FulfillmentCreateDateUTC
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> OEMPODateUTC
        {
            get;
            set;
        }
    
        public virtual string ShipToCustomerID
        {
            get;
            set;
        }
    
        public virtual string ShipToCustomerName
        {
            get;
            set;
        }
    
        public virtual string LicensableName
        {
            get;
            set;
        }
    
        public virtual string CallOffLineNumber
        {
            get;
            set;
        }
    
        public virtual string DeliveryNumber
        {
            get;
            set;
        }
    
        public virtual string DeliveryLineItemNumber
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Status
        {
            get;
            set;
        }
    
        public virtual byte ProductKeyStateID
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<HardwareBindingReport> HardwareBindingReports
        {
            get
            {
                if (_hardwareBindingReports == null)
                {
                    var newCollection = new FixupCollection<HardwareBindingReport>();
                    newCollection.CollectionChanged += FixupHardwareBindingReports;
                    _hardwareBindingReports = newCollection;
                }
                return _hardwareBindingReports;
            }
            set
            {
                if (!ReferenceEquals(_hardwareBindingReports, value))
                {
                    var previousValue = _hardwareBindingReports as FixupCollection<HardwareBindingReport>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupHardwareBindingReports;
                    }
                    _hardwareBindingReports = value;
                    var newValue = value as FixupCollection<HardwareBindingReport>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupHardwareBindingReports;
                    }
                }
            }
        }
        private ICollection<HardwareBindingReport> _hardwareBindingReports;
    
        public virtual ICollection<ReturnReportKey> ReturnReportKeys
        {
            get
            {
                if (_returnReportKeys == null)
                {
                    var newCollection = new FixupCollection<ReturnReportKey>();
                    newCollection.CollectionChanged += FixupReturnReportKeys;
                    _returnReportKeys = newCollection;
                }
                return _returnReportKeys;
            }
            set
            {
                if (!ReferenceEquals(_returnReportKeys, value))
                {
                    var previousValue = _returnReportKeys as FixupCollection<ReturnReportKey>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupReturnReportKeys;
                    }
                    _returnReportKeys = value;
                    var newValue = value as FixupCollection<ReturnReportKey>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupReturnReportKeys;
                    }
                }
            }
        }
        private ICollection<ReturnReportKey> _returnReportKeys;

        #endregion

        #region Association Fixup
    
        private void FixupHardwareBindingReports(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (HardwareBindingReport item in e.NewItems)
                {
                    item.ProductKeyInfo = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (HardwareBindingReport item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductKeyInfo, this))
                    {
                        item.ProductKeyInfo = null;
                    }
                }
            }
        }
    
        private void FixupReturnReportKeys(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ReturnReportKey item in e.NewItems)
                {
                    item.ProductKeyInfo = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ReturnReportKey item in e.OldItems)
                {
                    if (ReferenceEquals(item.ProductKeyInfo, this))
                    {
                        item.ProductKeyInfo = null;
                    }
                }
            }
        }

        #endregion

    }
}
