//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WcfService
{
    public partial class ReturnReport
    {
        #region Primitive Properties
    
        public virtual System.Guid ReturnUniqueID
        {
            get;
            set;
        }
    
        public virtual string MSReturnNumber
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ReturnDateUTC
        {
            get;
            set;
        }
    
        public virtual System.DateTime OEMRMADateUTC
        {
            get;
            set;
        }
    
        public virtual string OEMRMANumber
        {
            get;
            set;
        }
    
        public virtual string SoldToCustomerName
        {
            get;
            set;
        }
    
        public virtual System.DateTime OEMRMADate
        {
            get;
            set;
        }
    
        public virtual string SoldToCustomerID
        {
            get;
            set;
        }
    
        public virtual bool ReturnNoCredit
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> status
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<ReturnReportKey> ReturnReportKeys
        {
            get
            {
                if (_returnReportKeys == null)
                {
                    var newCollection = new FixupCollection<ReturnReportKey>();
                    newCollection.CollectionChanged += FixupReturnReportKeys;
                    _returnReportKeys = newCollection;
                }
                return _returnReportKeys;
            }
            set
            {
                if (!ReferenceEquals(_returnReportKeys, value))
                {
                    var previousValue = _returnReportKeys as FixupCollection<ReturnReportKey>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupReturnReportKeys;
                    }
                    _returnReportKeys = value;
                    var newValue = value as FixupCollection<ReturnReportKey>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupReturnReportKeys;
                    }
                }
            }
        }
        private ICollection<ReturnReportKey> _returnReportKeys;

        #endregion

        #region Association Fixup
    
        private void FixupReturnReportKeys(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ReturnReportKey item in e.NewItems)
                {
                    item.ReturnReport = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ReturnReportKey item in e.OldItems)
                {
                    if (ReferenceEquals(item.ReturnReport, this))
                    {
                        item.ReturnReport = null;
                    }
                }
            }
        }

        #endregion

    }
}
