//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.

namespace Platform.DAAS.OData.BusinessManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer() : base(String.Format("name={0}", ModuleConfiguration.DefaultBusinessStoreConnectionName))
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
            base.OnModelCreating(modelBuilder);
        }

        public DbSet<Business> Businesses { get; set; }
        public DbSet<Configuration> Configurations { get; set; }
    }
}
