//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace win81FactoryTest.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("win81FactoryTest.AppResources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer.
        /// </summary>
        internal static string Accelerometer {
            get {
                return ResourceManager.GetString("Accelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        internal static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALS .
        /// </summary>
        internal static string ALS {
            get {
                return ResourceManager.GetString("ALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Reading.
        /// </summary>
        internal static string ALSReading {
            get {
                return ResourceManager.GetString("ALSReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker and mic.
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file not found.
        /// </summary>
        internal static string AudioFileNotFound {
            get {
                return ResourceManager.GetString("AudioFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headset and Mic.
        /// </summary>
        internal static string AudioHeadset {
            get {
                return ResourceManager.GetString("AudioHeadset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please plug in [Headset], then click [Play]  Button to start playing audio. Click [Next] when audio finishes.
        /// </summary>
        internal static string AudioHeadsetPlay {
            get {
                return ResourceManager.GetString("AudioHeadsetPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please plug in [Headset], then click [Record] Button to start recording..
        /// </summary>
        internal static string AudioHeadsetRecord {
            get {
                return ResourceManager.GetString("AudioHeadsetRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string AudioNext {
            get {
                return ResourceManager.GetString("AudioNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string AudioPlay {
            get {
                return ResourceManager.GetString("AudioPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Audio file.
        /// </summary>
        internal static string AudioPlayAudio {
            get {
                return ResourceManager.GetString("AudioPlayAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        internal static string AudioRecording {
            get {
                return ResourceManager.GetString("AudioRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording now....
        /// </summary>
        internal static string AudioRecordingNow {
            get {
                return ResourceManager.GetString("AudioRecordingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove [Headset], then click [Play]  Button to start playing audio. Click [Next] when audio finishes.
        /// </summary>
        internal static string AudioSpeakerPlay {
            get {
                return ResourceManager.GetString("AudioSpeakerPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove [Headset], then click [Record] Button to start recording..
        /// </summary>
        internal static string AudioSpeakerRecord {
            get {
                return ResourceManager.GetString("AudioSpeakerRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string AudioStart {
            get {
                return ResourceManager.GetString("AudioStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string AudioStop {
            get {
                return ResourceManager.GetString("AudioStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery % :.
        /// </summary>
        internal static string Battery_bat {
            get {
                return ResourceManager.GetString("Battery_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging Rate :.
        /// </summary>
        internal static string Battery_chargeRate {
            get {
                return ResourceManager.GetString("Battery_chargeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Status :.
        /// </summary>
        internal static string Battery_chargeStatus {
            get {
                return ResourceManager.GetString("Battery_chargeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Status :.
        /// </summary>
        internal static string Battery_pwrStatus {
            get {
                return ResourceManager.GetString("Battery_pwrStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth.
        /// </summary>
        internal static string Bluetooth {
            get {
                return ResourceManager.GetString("Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start to test brightness.....
        /// </summary>
        internal static string Brightness_text {
            get {
                return ResourceManager.GetString("Brightness_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Brightness test.
        /// </summary>
        internal static string Brightness_text2 {
            get {
                return ResourceManager.GetString("Brightness_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        internal static string Compass {
            get {
                return ResourceManager.GetString("Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetic.
        /// </summary>
        internal static string CompassMagnetic {
            get {
                return ResourceManager.GetString("CompassMagnetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Display.
        /// </summary>
        internal static string ExternalDisplay {
            get {
                return ResourceManager.GetString("ExternalDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load media file.
        /// </summary>
        internal static string ExternalDisplay_Err {
            get {
                return ResourceManager.GetString("ExternalDisplay_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Camera.
        /// </summary>
        internal static string FrontCamera {
            get {
                return ResourceManager.GetString("FrontCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        internal static string GeolocationAccuracy {
            get {
                return ResourceManager.GetString("GeolocationAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string GeolocationLatitude {
            get {
                return ResourceManager.GetString("GeolocationLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string GeolocationLongitude {
            get {
                return ResourceManager.GetString("GeolocationLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        internal static string GPS {
            get {
                return ResourceManager.GetString("GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyrometer.
        /// </summary>
        internal static string Gyrometer {
            get {
                return ResourceManager.GetString("Gyrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Down.
        /// </summary>
        internal static string HardwareBtnVolumeDown {
            get {
                return ResourceManager.GetString("HardwareBtnVolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Up.
        /// </summary>
        internal static string HardwareBtnVolumeUp {
            get {
                return ResourceManager.GetString("HardwareBtnVolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Button.
        /// </summary>
        internal static string HardwareBtnWinBtn {
            get {
                return ResourceManager.GetString("HardwareBtnWinBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Button.
        /// </summary>
        internal static string HardwareButton {
            get {
                return ResourceManager.GetString("HardwareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate.
        /// </summary>
        internal static string Hibernate {
            get {
                return ResourceManager.GetString("Hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclinometer.
        /// </summary>
        internal static string Inclinometer {
            get {
                return ResourceManager.GetString("Inclinometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR Camera.
        /// </summary>
        internal static string IRCamera {
            get {
                return ResourceManager.GetString("IRCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashlight.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnetic heading.
        /// </summary>
        internal static string MagneticHeading {
            get {
                return ResourceManager.GetString("MagneticHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Not Found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen.
        /// </summary>
        internal static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser to clear Yellow.
        /// </summary>
        internal static string PenInstruction1 {
            get {
                return ResourceManager.GetString("PenInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear red dots.
        /// </summary>
        internal static string PenInstruction2 {
            get {
                return ResourceManager.GetString("PenInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear Camera.
        /// </summary>
        internal static string RearCamera {
            get {
                return ResourceManager.GetString("RearCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Drives.
        /// </summary>
        internal static string RemovableArgsDrive {
            get {
                return ResourceManager.GetString("RemovableArgsDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available space to current user.
        /// </summary>
        internal static string RemovableAvailableFreeSpace {
            get {
                return ResourceManager.GetString("RemovableAvailableFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable Device.
        /// </summary>
        internal static string RemovableDevice {
            get {
                return ResourceManager.GetString("RemovableDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive type.
        /// </summary>
        internal static string RemovableDriveType {
            get {
                return ResourceManager.GetString("RemovableDriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total available space.
        /// </summary>
        internal static string RemovableTotalFreeSpace {
            get {
                return ResourceManager.GetString("RemovableTotalFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size.
        /// </summary>
        internal static string RemovableTotalSize {
            get {
                return ResourceManager.GetString("RemovableTotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run All.
        /// </summary>
        internal static string RunAll {
            get {
                return ResourceManager.GetString("RunAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card.
        /// </summary>
        internal static string SIM {
            get {
                return ResourceManager.GetString("SIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM inserted.
        /// </summary>
        internal static string SIMFound {
            get {
                return ResourceManager.GetString("SIMFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM card not found.
        /// </summary>
        internal static string SIMNotFound {
            get {
                return ResourceManager.GetString("SIMNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string SysInfo {
            get {
                return ResourceManager.GetString("SysInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Info.
        /// </summary>
        internal static string SystemInfo {
            get {
                return ResourceManager.GetString("SystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch.
        /// </summary>
        internal static string Touch {
            get {
                return ResourceManager.GetString("Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchpad.
        /// </summary>
        internal static string Touchpad {
            get {
                return ResourceManager.GetString("Touchpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click.
        /// </summary>
        internal static string TouchpadDouble {
            get {
                return ResourceManager.GetString("TouchpadDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Click.
        /// </summary>
        internal static string TouchpadLeft {
            get {
                return ResourceManager.GetString("TouchpadLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Click.
        /// </summary>
        internal static string TouchpadRight {
            get {
                return ResourceManager.GetString("TouchpadRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all grid.
        /// </summary>
        internal static string TouchTest1 {
            get {
                return ResourceManager.GetString("TouchTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -touch point test: .
        /// </summary>
        internal static string TouchTest2 {
            get {
                return ResourceManager.GetString("TouchTest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe from left to right with {0} fingers.
        /// </summary>
        internal static string TouchTest3 {
            get {
                return ResourceManager.GetString("TouchTest3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True heading.
        /// </summary>
        internal static string TrueHeading {
            get {
                return ResourceManager.GetString("TrueHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait... .
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAxis.
        /// </summary>
        internal static string WAxis {
            get {
                return ResourceManager.GetString("WAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi.
        /// </summary>
        internal static string Wifi {
            get {
                return ResourceManager.GetString("Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Axis.
        /// </summary>
        internal static string XAxis {
            get {
                return ResourceManager.GetString("XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Degree.
        /// </summary>
        internal static string XDegree {
            get {
                return ResourceManager.GetString("XDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Axis.
        /// </summary>
        internal static string YAxis {
            get {
                return ResourceManager.GetString("YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Degree.
        /// </summary>
        internal static string YDegree {
            get {
                return ResourceManager.GetString("YDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Axit.
        /// </summary>
        internal static string ZAxis {
            get {
                return ResourceManager.GetString("ZAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Degree.
        /// </summary>
        internal static string ZDegree {
            get {
                return ResourceManager.GetString("ZDegree", resourceCulture);
            }
        }
    }
}
