//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.exportsummary
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class items { }
#else

	public class items : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public items()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/DIS;component/SampleData/exportsummary/exportsummary.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private itemCollection _itemCollection = new itemCollection();

		public itemCollection itemCollection
		{
			get
			{
				return this._itemCollection;
			}
		}
	}

	public class item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _mln = string.Empty;

		public string mln
		{
			get
			{
				return this._mln;
			}

			set
			{
				if (this._mln != value)
				{
					this._mln = value;
					this.OnPropertyChanged("mln");
				}
			}
		}

		private string _oempartnumber = string.Empty;

		public string oempartnumber
		{
			get
			{
				return this._oempartnumber;
			}

			set
			{
				if (this._oempartnumber != value)
				{
					this._oempartnumber = value;
					this.OnPropertyChanged("oempartnumber");
				}
			}
		}

		private double _exportquantity = 0;

		public double exportquantity
		{
			get
			{
				return this._exportquantity;
			}

			set
			{
				if (this._exportquantity != value)
				{
					this._exportquantity = value;
					this.OnPropertyChanged("exportquantity");
				}
			}
		}
	}

	public class itemCollection : System.Collections.ObjectModel.ObservableCollection<item>
	{ 
	}
#endif
}
