IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'NT AUTHORITY\LOCAL SERVICE')
BEGIN

    CREATE LOGIN [NT AUTHORITY\LOCAL SERVICE] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
    CREATE USER [NT AUTHORITY\LOCAL SERVICE] FOR LOGIN [NT AUTHORITY\LOCAL SERVICE];
END
GO

IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'NT AUTHORITY\SYSTEM')
BEGIN
    CREATE USER [NT AUTHORITY\SYSTEM] FOR LOGIN [NT AUTHORITY\SYSTEM];
END
GO

    EXEC sp_addrolemember 'db_datareader', 'NT AUTHORITY\LOCAL SERVICE';
    EXEC sp_addrolemember 'db_datawriter', 'NT AUTHORITY\LOCAL SERVICE';


    EXEC sp_addrolemember 'db_datareader', 'NT AUTHORITY\SYSTEM';
    EXEC sp_addrolemember 'db_datawriter', 'NT AUTHORITY\SYSTEM';

    GRANT EXECUTE ON [dbo].[AddCategory] TO [NT AUTHORITY\LOCAL SERVICE];
    GRANT EXECUTE ON [dbo].[ClearLogs] TO [NT AUTHORITY\LOCAL SERVICE];
    GRANT EXECUTE ON [dbo].[InsertCategoryLog] TO [NT AUTHORITY\LOCAL SERVICE];
    GRANT EXECUTE ON [dbo].[WriteLog] TO [NT AUTHORITY\LOCAL SERVICE];

