ALTER TABLE [dbo].[HardwareBindingReport]
    ADD CONSTRAINT [PK_HardwareBindingReport_1] PRIMARY KEY CLUSTERED ([ProductKeyID] ASC, [CustomerReportUniqueID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

