/*ALTER TABLE [dbo].[HardwareBindingReport]
    ADD CONSTRAINT [PK_HardwareBindingReport] PRIMARY KEY CLUSTERED ([ReportUniqueID] ASC, [ProductKeyID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

