ALTER TABLE [dbo].[ReturnReportKey]
    ADD CONSTRAINT [PK_ReturnReportKey] PRIMARY KEY CLUSTERED ([ReturnUniqueID] ASC, [ProductKeyID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

