ALTER TABLE [dbo].[ReturnReport]
    ADD CONSTRAINT [PK_ReturnReport_1] PRIMARY KEY CLUSTERED ([ReturnUniqueID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

