//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/DISConfigurationCloud.MetaManagement")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Configuration[] ConfigurationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Configuration[] Configurations {
            get {
                return this.ConfigurationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigurationsField, value) != true)) {
                    this.ConfigurationsField = value;
                    this.RaisePropertyChanged("Configurations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Configuration", Namespace="http://schemas.datacontract.org/2004/07/DISConfigurationCloud.MetaManagement")]
    [System.SerializableAttribute()]
    public partial class Configuration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.ConfigurationType ConfigurationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DbConnectionStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.ConfigurationType ConfigurationType {
            get {
                return this.ConfigurationTypeField;
            }
            set {
                if ((this.ConfigurationTypeField.Equals(value) != true)) {
                    this.ConfigurationTypeField = value;
                    this.RaisePropertyChanged("ConfigurationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DbConnectionString {
            get {
                return this.DbConnectionStringField;
            }
            set {
                if ((object.ReferenceEquals(this.DbConnectionStringField, value) != true)) {
                    this.DbConnectionStringField = value;
                    this.RaisePropertyChanged("DbConnectionString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurationType", Namespace="http://schemas.datacontract.org/2004/07/DISConfigurationCloud.MetaManagement")]
    public enum ConfigurationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OEM = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TPI = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FactoryFloor = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DISConfigurationCloudServiceReference.IDISConfigurationCloud")]
    public interface IDISConfigurationCloud {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDISConfigurationCloud/AddCustomer", ReplyAction="http://tempuri.org/IDISConfigurationCloud/AddCustomerResponse")]
        string AddCustomer(Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Customer Customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDISConfigurationCloud/AddCustomer", ReplyAction="http://tempuri.org/IDISConfigurationCloud/AddCustomerResponse")]
        System.Threading.Tasks.Task<string> AddCustomerAsync(Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Customer Customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDISConfigurationCloud/GetCustomer", ReplyAction="http://tempuri.org/IDISConfigurationCloud/GetCustomerResponse")]
        Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Customer GetCustomer(string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDISConfigurationCloud/GetCustomer", ReplyAction="http://tempuri.org/IDISConfigurationCloud/GetCustomerResponse")]
        System.Threading.Tasks.Task<Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Customer> GetCustomerAsync(string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDISConfigurationCloud/GetCustomers", ReplyAction="http://tempuri.org/IDISConfigurationCloud/GetCustomersResponse")]
        Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Customer[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDISConfigurationCloud/GetCustomers", ReplyAction="http://tempuri.org/IDISConfigurationCloud/GetCustomersResponse")]
        System.Threading.Tasks.Task<Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Customer[]> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDISConfigurationCloud/GetConfiguration", ReplyAction="http://tempuri.org/IDISConfigurationCloud/GetConfigurationResponse")]
        string GetConfiguration(string CustomerID, string ConfigurationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDISConfigurationCloud/GetConfiguration", ReplyAction="http://tempuri.org/IDISConfigurationCloud/GetConfigurationResponse")]
        System.Threading.Tasks.Task<string> GetConfigurationAsync(string CustomerID, string ConfigurationType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDISConfigurationCloudChannel : Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.IDISConfigurationCloud, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DISConfigurationCloudClient : System.ServiceModel.ClientBase<Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.IDISConfigurationCloud>, Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.IDISConfigurationCloud {
        
        public DISConfigurationCloudClient() {
        }
        
        public DISConfigurationCloudClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DISConfigurationCloudClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DISConfigurationCloudClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DISConfigurationCloudClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddCustomer(Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Customer Customer) {
            return base.Channel.AddCustomer(Customer);
        }
        
        public System.Threading.Tasks.Task<string> AddCustomerAsync(Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Customer Customer) {
            return base.Channel.AddCustomerAsync(Customer);
        }
        
        public Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Customer GetCustomer(string CustomerID) {
            return base.Channel.GetCustomer(CustomerID);
        }
        
        public System.Threading.Tasks.Task<Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Customer> GetCustomerAsync(string CustomerID) {
            return base.Channel.GetCustomerAsync(CustomerID);
        }
        
        public Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Customer[] GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<Test_DISConfigurationCloudServices.DISConfigurationCloudServiceReference.Customer[]> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public string GetConfiguration(string CustomerID, string ConfigurationType) {
            return base.Channel.GetConfiguration(CustomerID, ConfigurationType);
        }
        
        public System.Threading.Tasks.Task<string> GetConfigurationAsync(string CustomerID, string ConfigurationType) {
            return base.Channel.GetConfigurationAsync(CustomerID, ConfigurationType);
        }
    }
}
