//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.DAAS.OData.BusinessManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.Configuration = new HashSet<Configuration>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public string ReferenceId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime ModificationTime { get; set; }
    
        public virtual ICollection<Configuration> Configuration { get; set; }
    }
}
