//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.OrderDetails
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class Orders { }
#else

	public class Orders : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public Orders()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/DIS;component/SampleData/OrderDetails/OrderDetails.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private OrderCollection _OrderCollection = new OrderCollection();

		public OrderCollection OrderCollection
		{
			get
			{
				return this._OrderCollection;
			}
		}
	}

	public class Order : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _mspartnumber = string.Empty;

		public string mspartnumber
		{
			get
			{
				return this._mspartnumber;
			}

			set
			{
				if (this._mspartnumber != value)
				{
					this._mspartnumber = value;
					this.OnPropertyChanged("mspartnumber");
				}
			}
		}

		private string _oempartnumber = string.Empty;

		public string oempartnumber
		{
			get
			{
				return this._oempartnumber;
			}

			set
			{
				if (this._oempartnumber != value)
				{
					this._oempartnumber = value;
					this.OnPropertyChanged("oempartnumber");
				}
			}
		}

		private string _itemname = string.Empty;

		public string itemname
		{
			get
			{
				return this._itemname;
			}

			set
			{
				if (this._itemname != value)
				{
					this._itemname = value;
					this.OnPropertyChanged("itemname");
				}
			}
		}

		private double _quantity = 0;

		public double quantity
		{
			get
			{
				return this._quantity;
			}

			set
			{
				if (this._quantity != value)
				{
					this._quantity = value;
					this.OnPropertyChanged("quantity");
				}
			}
		}

		private string _requestedshipdate = string.Empty;

		public string requestedshipdate
		{
			get
			{
				return this._requestedshipdate;
			}

			set
			{
				if (this._requestedshipdate != value)
				{
					this._requestedshipdate = value;
					this.OnPropertyChanged("requestedshipdate");
				}
			}
		}

		private string _fulfilleddate = string.Empty;

		public string fulfilleddate
		{
			get
			{
				return this._fulfilleddate;
			}

			set
			{
				if (this._fulfilleddate != value)
				{
					this._fulfilleddate = value;
					this.OnPropertyChanged("fulfilleddate");
				}
			}
		}
	}

	public class OrderCollection : System.Collections.ObjectModel.ObservableCollection<Order>
	{ 
	}
#endif
}
