//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISConfigurationCloud.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public string Id { get; set; }
        public string CustomerId { get; set; }
        public int TypeId { get; set; }
        public string DbConnectionString { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
