ALTER TABLE [dbo].[TestParameter]
    ADD CONSTRAINT [PK_TestParameter] PRIMARY KEY CLUSTERED ([TestParameterID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

