ALTER TABLE [dbo].[Test]
    ADD CONSTRAINT [PK_Test] PRIMARY KEY CLUSTERED ([TestID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

