//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.validatereport
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class keys { }
#else

	public class keys : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public keys()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/DIS;component/SampleData/validatereport/validatereport.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private keyCollection _keyCollection = new keyCollection();

		public keyCollection keyCollection
		{
			get
			{
				return this._keyCollection;
			}
		}
	}

	public class key : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _productkey = string.Empty;

		public string productkey
		{
			get
			{
				return this._productkey;
			}

			set
			{
				if (this._productkey != value)
				{
					this._productkey = value;
					this.OnPropertyChanged("productkey");
				}
			}
		}

		private string _keystatus = string.Empty;

		public string keystatus
		{
			get
			{
				return this._keystatus;
			}

			set
			{
				if (this._keystatus != value)
				{
					this._keystatus = value;
					this.OnPropertyChanged("keystatus");
				}
			}
		}

		private string _validateresult = string.Empty;

		public string validateresult
		{
			get
			{
				return this._validateresult;
			}

			set
			{
				if (this._validateresult != value)
				{
					this._validateresult = value;
					this.OnPropertyChanged("validateresult");
				}
			}
		}

		private string _description = string.Empty;

		public string description
		{
			get
			{
				return this._description;
			}

			set
			{
				if (this._description != value)
				{
					this._description = value;
					this.OnPropertyChanged("description");
				}
			}
		}
	}

	public class keyCollection : System.Collections.ObjectModel.ObservableCollection<key>
	{ 
	}
#endif
}
