//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.WorkPackages = new HashSet<WorkPackage>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public string BusinessID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<WorkPackage> WorkPackages { get; set; }
    }
}
