//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OriginalFile
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public byte[] Content { get; set; }
        public string TransactionID { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
