//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductKeyIDSerialNumberPairs
    {
        public System.Guid PairID { get; set; }
        public Nullable<long> ProductKeyID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string TransactionID { get; set; }
    }
}
