//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.OriginalFiles = new HashSet<OriginalFile>();
        }
    
        public string ID { get; set; }
        public string WorkPackageID { get; set; }
        public string ReferenceID { get; set; }
        public long ProductKeyID { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime SynchronizationTime { get; set; }
    
        public virtual WorkPackage WorkPackage { get; set; }
        public virtual ICollection<OriginalFile> OriginalFiles { get; set; }
    }
}
