//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string ID { get; set; }
        public string FullName { get; set; }
        public string LoginName { get; set; }
        public string PasswordHash { get; set; }
        public string Description { get; set; }
        public int State { get; set; }
    
        public virtual WorkPackage WorkPackage { get; set; }
        public virtual Role Role { get; set; }
    }
}
