//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPackage
    {
        public WorkPackage()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string ID { get; set; }
        public string ModelID { get; set; }
        public string Name { get; set; }
        public int State { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual User User { get; set; }
    }
}
