CREATE NONCLUSTERED INDEX [IX_ProductKeyInfo_ZTOUCH_SCREEN] ON [dbo].[ProductKeyInfo](	[ZTOUCH_SCREEN] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] 

