//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Platform.DAAS.OData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ServiceConsumptions = new HashSet<ServiceConsumption>();
            this.ServiceSubscriptions = new HashSet<ServiceSubscription>();
        }
    
        public string ID { get; set; }
        public string ApplicationID { get; set; }
        public string Name { get; set; }
        public int DBType { get; set; }
        public int ServiceType { get; set; }
        public string ResourceName { get; set; }
        public string DBConnectionString { get; set; }
        public string Url { get; set; }
        public string Address { get; set; }
        public string Port { get; set; }
        public string Parameters { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Charset { get; set; }
        public string ContentType { get; set; }
        public string DomainName { get; set; }
        public Nullable<long> Size { get; set; }
        public string ModelMeta { get; set; }
        public string ServiceCode { get; set; }
        public byte[] Binary { get; set; }
        public string Version { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationTime { get; set; }
    
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceConsumption> ServiceConsumptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceSubscription> ServiceSubscriptions { get; set; }
    }
}
