//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISConfigurationCloud {
    
    
    public partial class RestoreDatabase {
        
        /// <summary>
        /// CustomerDatabaseSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DISConfigurationCloud.UserControls.CustomerDatabaseSelector CustomerDatabaseSelector;
        
        /// <summary>
        /// DBBackupDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DISConfigurationCloud.UserControls.DBBackupDetail DBBackupDetail;
        
        /// <summary>
        /// ButtonRestoreDatabase control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonRestoreDatabase;
    }
}
