//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.OrderLineItems
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class Items { }
#else

	public class Items : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public Items()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/DIS;component/SampleData/OrderLineItems/OrderLineItems.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _ItemCollection = new ItemCollection();

		public ItemCollection ItemCollection
		{
			get
			{
				return this._ItemCollection;
			}
		}
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _mspartnumber = string.Empty;

		public string mspartnumber
		{
			get
			{
				return this._mspartnumber;
			}

			set
			{
				if (this._mspartnumber != value)
				{
					this._mspartnumber = value;
					this.OnPropertyChanged("mspartnumber");
				}
			}
		}

		private string _oempartnumber = string.Empty;

		public string oempartnumber
		{
			get
			{
				return this._oempartnumber;
			}

			set
			{
				if (this._oempartnumber != value)
				{
					this._oempartnumber = value;
					this.OnPropertyChanged("oempartnumber");
				}
			}
		}

		private double _quantity = 0;

		public double quantity
		{
			get
			{
				return this._quantity;
			}

			set
			{
				if (this._quantity != value)
				{
					this._quantity = value;
					this.OnPropertyChanged("quantity");
				}
			}
		}

		private string _requestedshipdate = string.Empty;

		public string requestedshipdate
		{
			get
			{
				return this._requestedshipdate;
			}

			set
			{
				if (this._requestedshipdate != value)
				{
					this._requestedshipdate = value;
					this.OnPropertyChanged("requestedshipdate");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
