//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS.Presentation.KMT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIS.Presentation.KMT.Properties.NewResources", typeof(NewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have assigned {0} keys.
        /// </summary>
        public static string AssignKeysViewModel_AssignKeysLog {
            get {
                return ResourceManager.GetString("AssignKeysViewModel_AssignKeysLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack File Date.
        /// </summary>
        public static string Common_ColumnHeaderAckFileDate {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderAckFileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer  Name .
        /// </summary>
        public static string Common_ColumnHeaderCustomerName {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Number.
        /// </summary>
        public static string Common_ColumnHeaderCustomerNumber {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderCustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Common_ColumnHeaderPassword {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Common_ColumnHeaderPhone {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship To.
        /// </summary>
        public static string Common_ColumnHeaderShipTo {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold To.
        /// </summary>
        public static string Common_ColumnHeaderSoldTo {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderSoldTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Common_ColumnHeaderType {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Common_Copy {
            get {
                return ResourceManager.GetString("Common_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic.
        /// </summary>
        public static string Common_Diagnostic {
            get {
                return ResourceManager.GetString("Common_Diagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Common_Exit {
            get {
                return ResourceManager.GetString("Common_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal web service returned error : {0}..
        /// </summary>
        public static string Common_InternalErrorFormat {
            get {
                return ResourceManager.GetString("Common_InternalErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_SaveFileTitle {
            get {
                return ResourceManager.GetString("Common_SaveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Common_View {
            get {
                return ResourceManager.GetString("Common_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt files (*.xml)|*.xml.
        /// </summary>
        public static string Common_XmlFilter {
            get {
                return ResourceManager.GetString("Common_XmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfilled Date To.
        /// </summary>
        public static string CommonDate_To {
            get {
                return ResourceManager.GetString("CommonDate_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required!.
        /// </summary>
        public static string CreateUserViewModel_RequriedLoginId {
            get {
                return ResourceManager.GetString("CreateUserViewModel_RequriedLoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} format is invalid!.
        /// </summary>
        public static string CreateUserViewModel_WrongEmailFormat {
            get {
                return ResourceManager.GetString("CreateUserViewModel_WrongEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} format is invalid!.
        /// </summary>
        public static string CreateUserViewModel_WrongPhoneNumber {
            get {
                return ResourceManager.GetString("CreateUserViewModel_WrongPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to internal web service.
        /// </summary>
        public static string Diagnostic_InternalConnection {
            get {
                return ResourceManager.GetString("Diagnostic_InternalConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Microsoft web service.
        /// </summary>
        public static string Diagnostic_MicrosoftConnection {
            get {
                return ResourceManager.GetString("Diagnostic_MicrosoftConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Diagnostic_Test {
            get {
                return ResourceManager.GetString("Diagnostic_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connection to internal web service ....
        /// </summary>
        public static string Diagnostic_TestingInternal {
            get {
                return ResourceManager.GetString("Diagnostic_TestingInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connection to Microsoft web service ....
        /// </summary>
        public static string Diagnostic_TestingMicrosoft {
            get {
                return ResourceManager.GetString("Diagnostic_TestingMicrosoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connection to up level system ....
        /// </summary>
        public static string Diagnostic_TestingULS {
            get {
                return ResourceManager.GetString("Diagnostic_TestingULS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic.
        /// </summary>
        public static string Diagnostic_Title {
            get {
                return ResourceManager.GetString("Diagnostic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to up level system.
        /// </summary>
        public static string Diagnostic_ULSConnection {
            get {
                return ResourceManager.GetString("Diagnostic_ULSConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Not Found!.
        /// </summary>
        public static string Exception_CertificateNotFound {
            get {
                return ResourceManager.GetString("Exception_CertificateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate error,please try run it as administrator..
        /// </summary>
        public static string Exception_GetprivateKeyError {
            get {
                return ResourceManager.GetString("Exception_GetprivateKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file content is not correct, please confirm it..
        /// </summary>
        public static string Exception_ImportFileInvalid {
            get {
                return ResourceManager.GetString("Exception_ImportFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permissions error, please run it as administrator!.
        /// </summary>
        public static string Exception_PermissionsMsg {
            get {
                return ResourceManager.GetString("Exception_PermissionsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        public static string ExportKey_Encryptselect {
            get {
                return ResourceManager.GetString("ExportKey_Encryptselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The detail key(s) of  the Log File.
        /// </summary>
        public static string ExportKey_FileKeysTitle {
            get {
                return ResourceManager.GetString("ExportKey_FileKeysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File location:.
        /// </summary>
        public static string ExportKey_FileLocation {
            get {
                return ResourceManager.GetString("ExportKey_FileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export quality more than 5000 keys .
        /// </summary>
        public static string ExportKey_LimitQualityMsg {
            get {
                return ResourceManager.GetString("ExportKey_LimitQualityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export file without encrypt is a high security risk, are you sure?.
        /// </summary>
        public static string ExportKey_NonEncryptMsg {
            get {
                return ResourceManager.GetString("ExportKey_NonEncryptMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one file can be Re-Exported at a time..
        /// </summary>
        public static string ExportKey_SelectSingle {
            get {
                return ResourceManager.GetString("ExportKey_SelectSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Duplicate CBR Key(s).
        /// </summary>
        public static string ExportKeys_ExportDuplicateCBR {
            get {
                return ResourceManager.GetString("ExportKeys_ExportDuplicateCBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CBR.
        /// </summary>
        public static string ExportKeysViewModel_ExportCBRTxt {
            get {
                return ResourceManager.GetString("ExportKeysViewModel_ExportCBRTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Duplicate CBR.
        /// </summary>
        public static string ExportKeysViewModel_ExportDuplicateCBRTxt {
            get {
                return ResourceManager.GetString("ExportKeysViewModel_ExportDuplicateCBRTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exported {0} key(s) successfully..
        /// </summary>
        public static string ExportKeysViewModel_FinishTxt {
            get {
                return ResourceManager.GetString("ExportKeysViewModel_FinishTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-export Keys.
        /// </summary>
        public static string ExportKeysViewModel_ReExportKey {
            get {
                return ResourceManager.GetString("ExportKeysViewModel_ReExportKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-export Keys for OA3Tool.
        /// </summary>
        public static string ExportKeysViewModel_ReExportOA3Key {
            get {
                return ResourceManager.GetString("ExportKeysViewModel_ReExportOA3Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file cannot be found..
        /// </summary>
        public static string ImportKey_FileNotExists {
            get {
                return ResourceManager.GetString("ImportKey_FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Keys.
        /// </summary>
        public static string ImportKey_RbKeytxt {
            get {
                return ResourceManager.GetString("ImportKey_RbKeytxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Keys is not from current UP lever Source,please confirm it!.
        /// </summary>
        public static string ImportKey_SourceFromError {
            get {
                return ResourceManager.GetString("ImportKey_SourceFromError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import  Duplicate CBR.
        /// </summary>
        public static string ImportKeysViewModel_ImportDuplicateCBRTxt {
            get {
                return ResourceManager.GetString("ImportKeysViewModel_ImportDuplicateCBRTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated CBR {0} was import..
        /// </summary>
        public static string ImportKeysViewModel_ImportDuplicatedCBRTxt {
            get {
                return ResourceManager.GetString("ImportKeysViewModel_ImportDuplicatedCBRTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} duplicated CBR(s).
        /// </summary>
        public static string KeyManagementViewModel_DuplicateCBRsMessage {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_DuplicateCBRsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0} key(s) successfully !.
        /// </summary>
        public static string KeyManagementViewModel_GetKeySuccess {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_GetKeySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No keys available..
        /// </summary>
        public static string KeyManagementViewModel_NoKeyGet {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_NoKeyGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert Keys.
        /// </summary>
        public static string MainWindow_MarkAsFulfilled {
            get {
                return ResourceManager.GetString("MainWindow_MarkAsFulfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall Key.
        /// </summary>
        public static string MainWindow_Recall {
            get {
                return ResourceManager.GetString("MainWindow_Recall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall Keys.
        /// </summary>
        public static string MainWindow_RecallKeys {
            get {
                return ResourceManager.GetString("MainWindow_RecallKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove User.
        /// </summary>
        public static string MainWindow_RemoveUser {
            get {
                return ResourceManager.GetString("MainWindow_RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert Keys.
        /// </summary>
        public static string MarkFulfilledKeys_WindowTitle {
            get {
                return ResourceManager.GetString("MarkFulfilledKeys_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore {0} successfully!.
        /// </summary>
        public static string ProcessDuplicateKeysViewModel_HadleIgnoreKeys {
            get {
                return ResourceManager.GetString("ProcessDuplicateKeysViewModel_HadleIgnoreKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select key(s) to recall!..
        /// </summary>
        public static string RecallKeysViewModel_NotSelectKeys {
            get {
                return ResourceManager.GetString("RecallKeysViewModel_NotSelectKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have recalled {0} key(s) successfully..
        /// </summary>
        public static string RecallKeysViewModel_RecallKeysResult {
            get {
                return ResourceManager.GetString("RecallKeysViewModel_RecallKeysResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have recalled {0} keys..
        /// </summary>
        public static string RecallKeysViewModel_TxtRecallLog {
            get {
                return ResourceManager.GetString("RecallKeysViewModel_TxtRecallLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Keys.
        /// </summary>
        public static string ReportKeysViewModel_ReportKeysTitle {
            get {
                return ResourceManager.GetString("ReportKeysViewModel_ReportKeysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of Revert :.
        /// </summary>
        public static string SummaryView_MarkFulfilledPrompt {
            get {
                return ResourceManager.GetString("SummaryView_MarkFulfilledPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to change Up Level System settings?.
        /// </summary>
        public static string UpLevelSystemViewModel_SavingConfirm {
            get {
                return ResourceManager.GetString("UpLevelSystemViewModel_SavingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web service host or port is invalid!.
        /// </summary>
        public static string WebServiceHostOrPortInvalid {
            get {
                return ResourceManager.GetString("WebServiceHostOrPortInvalid", resourceCulture);
            }
        }
    }
}
