//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS.Presentation.KMT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesOfRTMv1_8 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesOfRTMv1_8() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIS.Presentation.KMT.Properties.ResourcesOfRTMv1.8", typeof(ResourcesOfRTMv1_8).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Description.
        /// </summary>
        public static string Common_ColumnHeaderErrorDescription {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Common_Fail {
            get {
                return ResourceManager.GetString("Common_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Factor Class.
        /// </summary>
        public static string EditOptionalInfo_ColumnHeaderFactor1 {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ColumnHeaderFactor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Factor Sub Class.
        /// </summary>
        public static string EditOptionalInfo_ColumnHeaderFactor2 {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ColumnHeaderFactor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Size.
        /// </summary>
        public static string EditOptionalInfo_ColumnHeaderScreenSize {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ColumnHeaderScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Screen.
        /// </summary>
        public static string EditOptionalInfo_ColumnHeaderTouchScreen {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ColumnHeaderTouchScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export OHR to MS.
        /// </summary>
        public static string Export_OHRTxt {
            get {
                return ResourceManager.GetString("Export_OHRTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import OHR ACK. from MS.
        /// </summary>
        public static string Import_OHRAckTxt {
            get {
                return ResourceManager.GetString("Import_OHRAckTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OHR Data Update.
        /// </summary>
        public static string MainWindow_OHR {
            get {
                return ResourceManager.GetString("MainWindow_OHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get fulfillment failed, your database is full. Please extended your databas space, and do a refulfillment..
        /// </summary>
        public static string Notification_DatabaseDiskFull {
            get {
                return ResourceManager.GetString("Notification_DatabaseDiskFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Move your mouse over the field to get the error description.].
        /// </summary>
        public static string OhrKeysNotificationView_Help {
            get {
                return ResourceManager.GetString("OhrKeysNotificationView_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There have {0} key(s) are updated unsuccessfully..
        /// </summary>
        public static string OhrKeysNotificationViewModel_Summary {
            get {
                return ResourceManager.GetString("OhrKeysNotificationViewModel_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All 5 fields of OHR data are required..
        /// </summary>
        public static string OhrUpdateViewModel_InvalideOhrData {
            get {
                return ResourceManager.GetString("OhrUpdateViewModel_InvalideOhrData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update some fields of OHR data..
        /// </summary>
        public static string OhrUpdateViewModel_Message {
            get {
                return ResourceManager.GetString("OhrUpdateViewModel_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OHR Data Update keys :  {0} successful, {1}  failed.
        /// </summary>
        public static string OhrUpdateViewModel_OhrResult {
            get {
                return ResourceManager.GetString("OhrUpdateViewModel_OhrResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected keys have invalidate touch screen value..
        /// </summary>
        public static string ReportKeysViewModel_InvalidateTouchScreen {
            get {
                return ResourceManager.GetString("ReportKeysViewModel_InvalidateTouchScreen", resourceCulture);
            }
        }
    }
}
