//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS.Presentation.KMT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesOfRTMv1_6 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesOfRTMv1_6() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIS.Presentation.KMT.Properties.ResourcesOfRTMv1.6", typeof(ResourcesOfRTMv1_6).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Factor Class:.
        /// </summary>
        public static string EditOptionalInfo_Factor1Name {
            get {
                return ResourceManager.GetString("EditOptionalInfo_Factor1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Factor Sub Class:.
        /// </summary>
        public static string EditOptionalInfo_Factor2Name {
            get {
                return ResourceManager.GetString("EditOptionalInfo_Factor2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report keys contains missing OHR Data,do you continue to report?.
        /// </summary>
        public static string EditOptionalInfo_MissOHRDataMsg {
            get {
                return ResourceManager.GetString("EditOptionalInfo_MissOHRDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keys contains OHR Data,do you continue to overwrite?.
        /// </summary>
        public static string EditOptionalInfo_OverWriteOHRDataMsg {
            get {
                return ResourceManager.GetString("EditOptionalInfo_OverWriteOHRDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill up missed OHR data for optional info before reporting keys to Microsoft..
        /// </summary>
        public static string EditOptionalInfo_RequireOHRDataMsg {
            get {
                return ResourceManager.GetString("EditOptionalInfo_RequireOHRDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Size:.
        /// </summary>
        public static string EditOptionalInfo_ScreenSizeName {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ScreenSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Screen:.
        /// </summary>
        public static string EditOptionalInfo_TouchScreenName {
            get {
                return ResourceManager.GetString("EditOptionalInfo_TouchScreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZFRM_FACTOR_CL1.
        /// </summary>
        public static string EditOptionalInfo_zFactor1 {
            get {
                return ResourceManager.GetString("EditOptionalInfo_zFactor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZFRM_FACTOR_CL2.
        /// </summary>
        public static string EditOptionalInfo_zFactor2 {
            get {
                return ResourceManager.GetString("EditOptionalInfo_zFactor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZSCREEN_SIZE.
        /// </summary>
        public static string EditOptionalInfo_zScreenSize {
            get {
                return ResourceManager.GetString("EditOptionalInfo_zScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZTOUCH_SCREEN.
        /// </summary>
        public static string EditOptionalInfo_zTouchScerrn {
            get {
                return ResourceManager.GetString("EditOptionalInfo_zTouchScerrn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string NoAssignLabel {
            get {
                return ResourceManager.GetString("NoAssignLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Bound key(s) missed OHR Data..
        /// </summary>
        public static string OhrDataMissedFormat {
            get {
                return ResourceManager.GetString("OhrDataMissedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark OHR Data as required.
        /// </summary>
        public static string RequireOHRDataLabel {
            get {
                return ResourceManager.GetString("RequireOHRDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Type ID:.
        /// </summary>
        public static string ReturnTypeLabel {
            get {
                return ResourceManager.GetString("ReturnTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the Screen Size value, it&apos;s decimal or number format..
        /// </summary>
        public static string ScreenValueFormatMsg {
            get {
                return ResourceManager.GetString("ScreenValueFormatMsg", resourceCulture);
            }
        }
    }
}
