//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS.Presentation.KMT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesOfR6 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesOfR6() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIS.Presentation.KMT.Properties.ResourcesOfR6", typeof(ResourcesOfR6).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a certificate.
        /// </summary>
        public static string CertVM_CertPickerTitle {
            get {
                return ResourceManager.GetString("CertVM_CertPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All returned keys.
        /// </summary>
        public static string Common_AllReturnedKeys {
            get {
                return ResourceManager.GetString("Common_AllReturnedKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  :.
        /// </summary>
        public static string Common_ColumnSemicolon {
            get {
                return ResourceManager.GetString("Common_ColumnSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Status.
        /// </summary>
        public static string Common_ColumnStatus {
            get {
                return ResourceManager.GetString("Common_ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Common_CreditSelect {
            get {
                return ResourceManager.GetString("Common_CreditSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLS Name.
        /// </summary>
        public static string Common_DLSName {
            get {
                return ResourceManager.GetString("Common_DLSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLS Name :.
        /// </summary>
        public static string Common_DLSName1 {
            get {
                return ResourceManager.GetString("Common_DLSName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown exception, please contact administrator and check the log..
        /// </summary>
        public static string Common_GeneralExceptionMsg {
            get {
                return ResourceManager.GetString("Common_GeneralExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Common_Host1 {
            get {
                return ResourceManager.GetString("Common_Host1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Type.
        /// </summary>
        public static string Common_KeyType {
            get {
                return ResourceManager.GetString("Common_KeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Type :.
        /// </summary>
        public static string Common_KeyType1 {
            get {
                return ResourceManager.GetString("Common_KeyType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBR key.
        /// </summary>
        public static string Common_MotherBoardReplacementKey {
            get {
                return ResourceManager.GetString("Common_MotherBoardReplacementKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAT key.
        /// </summary>
        public static string Common_MultipleActivationTestKey {
            get {
                return ResourceManager.GetString("Common_MultipleActivationTestKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to report {0} keys..
        /// </summary>
        public static string Common_ReportedKeyFailed {
            get {
                return ResourceManager.GetString("Common_ReportedKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Keys Failed.
        /// </summary>
        public static string Common_ReportedKeyFailedTitle {
            get {
                return ResourceManager.GetString("Common_ReportedKeyFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: These failed keys will be reported by Data Polling automatically..
        /// </summary>
        public static string Common_ReportFailed {
            get {
                return ResourceManager.GetString("Common_ReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to return {0} keys..
        /// </summary>
        public static string Common_ReturnedKeyFailed {
            get {
                return ResourceManager.GetString("Common_ReturnedKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Keys Failed.
        /// </summary>
        public static string Common_ReturnedKeyFailedTitle {
            get {
                return ResourceManager.GetString("Common_ReturnedKeyFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned with credit.
        /// </summary>
        public static string Common_ReturnedWithCredit {
            get {
                return ResourceManager.GetString("Common_ReturnedWithCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned with no credit.
        /// </summary>
        public static string Common_ReturnedWithNoCredit {
            get {
                return ResourceManager.GetString("Common_ReturnedWithNoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (español).
        /// </summary>
        public static string Common_Spanish {
            get {
                return ResourceManager.GetString("Common_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard key.
        /// </summary>
        public static string Common_StandardKey {
            get {
                return ResourceManager.GetString("Common_StandardKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Status.
        /// </summary>
        public static string Common_SystemStatus {
            get {
                return ResourceManager.GetString("Common_SystemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULS Name.
        /// </summary>
        public static string Common_ULSName {
            get {
                return ResourceManager.GetString("Common_ULSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULS Name :.
        /// </summary>
        public static string Common_ULSName1 {
            get {
                return ResourceManager.GetString("Common_ULSName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to down level system.
        /// </summary>
        public static string Diagnostic_DLSConnection {
            get {
                return ResourceManager.GetString("Diagnostic_DLSConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection to down level system.....
        /// </summary>
        public static string Diagnostic_TestingDLS {
            get {
                return ResourceManager.GetString("Diagnostic_TestingDLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check status of system components automatically.
        /// </summary>
        public static string DiagnosticView_AutoDiagnostic {
            get {
                return ResourceManager.GetString("DiagnosticView_AutoDiagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Down Level System to diagnose..
        /// </summary>
        public static string DiagnosticVM_SSIdNotEmpty {
            get {
                return ResourceManager.GetString("DiagnosticVM_SSIdNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLS Name already exists..
        /// </summary>
        public static string DLSVM_DLSNameExists {
            get {
                return ResourceManager.GetString("DLSVM_DLSNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLS Name is required..
        /// </summary>
        public static string DLSVM_DLSNameNotEmpty {
            get {
                return ResourceManager.GetString("DLSVM_DLSNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name already exists..
        /// </summary>
        public static string DLSVM_UserNameExists {
            get {
                return ResourceManager.GetString("DLSVM_UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Export_OpenFolder {
            get {
                return ResourceManager.GetString("Export_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Export Return Keys to MS.
        /// </summary>
        public static string Export_ReReturnKeyTxt {
            get {
                return ResourceManager.GetString("Export_ReReturnKeyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Export_ReturnHeader {
            get {
                return ResourceManager.GetString("Export_ReturnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Return Keys to MS.
        /// </summary>
        public static string Export_ReturnKeyTxt {
            get {
                return ResourceManager.GetString("Export_ReturnKeyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OEM RMA Date must be within +/-5 years from now..
        /// </summary>
        public static string Export_ReturnRMADateInvalid {
            get {
                return ResourceManager.GetString("Export_ReturnRMADateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the OEM RMA Date.
        /// </summary>
        public static string Export_ReturnRMADateMsg {
            get {
                return ResourceManager.GetString("Export_ReturnRMADateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Return Keys.
        /// </summary>
        public static string Export_SelectReturnKey_Tit {
            get {
                return ResourceManager.GetString("Export_SelectReturnKey_Tit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive :.
        /// </summary>
        public static string ExportLog_ArchiveInput {
            get {
                return ResourceManager.GetString("ExportLog_ArchiveInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete exported logs.
        /// </summary>
        public static string ExportLog_ArchiveLabel {
            get {
                return ResourceManager.GetString("ExportLog_ArchiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return ACK..
        /// </summary>
        public static string Import_ReturnACKHeader {
            get {
                return ResourceManager.GetString("Import_ReturnACKHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Return ACK. from MS.
        /// </summary>
        public static string Import_ReturnAckTxt {
            get {
                return ResourceManager.GetString("Import_ReturnAckTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfill key from Microsoft failed!.
        /// </summary>
        public static string KeyManagementViewModel_FulfillmentFail {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_FulfillmentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Type Configuration.
        /// </summary>
        public static string KeyTypeConfigurationView_Title {
            get {
                return ResourceManager.GetString("KeyTypeConfigurationView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensable part number and key type mapping can not be changed later, are you sure to save the configuration?.
        /// </summary>
        public static string KeyTypeConfigurationVM_SaveConfirm {
            get {
                return ResourceManager.GetString("KeyTypeConfigurationVM_SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Keys.
        /// </summary>
        public static string MainWindow_ReturnKeys {
            get {
                return ResourceManager.GetString("MainWindow_ReturnKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Base dose not work!.
        /// </summary>
        public static string Notification_DataBaseErrorMessage {
            get {
                return ResourceManager.GetString("Notification_DataBaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Polling does not work!.
        /// </summary>
        public static string Notification_DatePollingErrorMessage {
            get {
                return ResourceManager.GetString("Notification_DatePollingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down level system(s) does not work! {0}.
        /// </summary>
        public static string Notification_DownLevelSystemErrorMessage {
            get {
                return ResourceManager.GetString("Notification_DownLevelSystemErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal web service does not work!.
        /// </summary>
        public static string Notification_InternalErrorMessage {
            get {
                return ResourceManager.GetString("Notification_InternalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key provider service dose not work!.
        /// </summary>
        public static string Notification_KeyProviderServiceErrorMessage {
            get {
                return ResourceManager.GetString("Notification_KeyProviderServiceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to Microsoft web service!.
        /// </summary>
        public static string Notification_MSConnectionErrorMessage {
            get {
                return ResourceManager.GetString("Notification_MSConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state is unknown!.
        /// </summary>
        public static string Notification_UnknowMessage {
            get {
                return ResourceManager.GetString("Notification_UnknowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up level system does not work!.
        /// </summary>
        public static string Notification_UpLevelSystemErrorMessage {
            get {
                return ResourceManager.GetString("Notification_UpLevelSystemErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system contains licensable part number that not mapped to key type..
        /// </summary>
        public static string Notification_UpmapKeyPartNumber {
            get {
                return ResourceManager.GetString("Notification_UpmapKeyPartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   System Notifications ({0}).
        /// </summary>
        public static string Notification_YouHaveSystemNotifications {
            get {
                return ResourceManager.GetString("Notification_YouHaveSystemNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to return keys that will not receive credit?.
        /// </summary>
        public static string ReturnKeysView_CreditTitle {
            get {
                return ResourceManager.GetString("ReturnKeysView_CreditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, don&apos;t return keys that will not receive credit. (Default)..
        /// </summary>
        public static string ReturnKeysView_NoCredit {
            get {
                return ResourceManager.GetString("ReturnKeysView_NoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input OEM RMA Number!.
        /// </summary>
        public static string ReturnKeysView_NoOemRmaNumberError {
            get {
                return ResourceManager.GetString("ReturnKeysView_NoOemRmaNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM RMA Date :.
        /// </summary>
        public static string ReturnKeysView_OEMRMADate {
            get {
                return ResourceManager.GetString("ReturnKeysView_OEMRMADate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM RMA Number :.
        /// </summary>
        public static string ReturnKeysView_OEMRMANumber {
            get {
                return ResourceManager.GetString("ReturnKeysView_OEMRMANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM RMA Number is too long. .
        /// </summary>
        public static string ReturnKeysView_OemRmaNumberError {
            get {
                return ResourceManager.GetString("ReturnKeysView_OemRmaNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without credit .
        /// </summary>
        public static string ReturnKeysView_ReturnNoCredit {
            get {
                return ResourceManager.GetString("ReturnKeysView_ReturnNoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure return keys without credit?.
        /// </summary>
        public static string ReturnKeysView_ReturnNoCreditWaring {
            get {
                return ResourceManager.GetString("ReturnKeysView_ReturnNoCreditWaring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system with the specified key may have been shipped to the end user!.
        /// </summary>
        public static string ReturnKeysView_ReturnNotice {
            get {
                return ResourceManager.GetString("ReturnKeysView_ReturnNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Type Description.
        /// </summary>
        public static string ReturnKeysView_ReturnType {
            get {
                return ResourceManager.GetString("ReturnKeysView_ReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Keys.
        /// </summary>
        public static string ReturnKeysView_Title {
            get {
                return ResourceManager.GetString("ReturnKeysView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, return keys even if they will not receive credit..
        /// </summary>
        public static string ReturnKeysView_YesCredit {
            get {
                return ResourceManager.GetString("ReturnKeysView_YesCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Documentation Required.
        /// </summary>
        public static string ReturnKeysView_ZOADescription {
            get {
                return ResourceManager.GetString("ReturnKeysView_ZOADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User.
        /// </summary>
        public static string ReturnKeysView_ZOBDescription {
            get {
                return ResourceManager.GetString("ReturnKeysView_ZOBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Damage.
        /// </summary>
        public static string ReturnKeysView_ZOCDescription {
            get {
                return ResourceManager.GetString("ReturnKeysView_ZOCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Key.
        /// </summary>
        public static string ReturnKeysView_ZODDescription {
            get {
                return ResourceManager.GetString("ReturnKeysView_ZODDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost/Stolen.
        /// </summary>
        public static string ReturnKeysView_ZOEDescription {
            get {
                return ResourceManager.GetString("ReturnKeysView_ZOEDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other (no credit).
        /// </summary>
        public static string ReturnKeysView_ZOFDescription {
            get {
                return ResourceManager.GetString("ReturnKeysView_ZOFDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned keys :  {0} successful,  {1} failed.
        /// </summary>
        public static string ReturnKeysViewModel_ReturnSuccess {
            get {
                return ResourceManager.GetString("ReturnKeysViewModel_ReturnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input revert message..
        /// </summary>
        public static string RevertKey_InputMsg {
            get {
                return ResourceManager.GetString("RevertKey_InputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS certificate :.
        /// </summary>
        public static string SystemSettingView_MSCert {
            get {
                return ResourceManager.GetString("SystemSettingView_MSCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Url :.
        /// </summary>
        public static string SystemSettingView_MSUrl {
            get {
                return ResourceManager.GetString("SystemSettingView_MSUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centralized Mode.
        /// </summary>
        public static string ULSView_Centralize {
            get {
                return ResourceManager.GetString("ULSView_Centralize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decentralized Mode.
        /// </summary>
        public static string ULSView_Decentralize {
            get {
                return ResourceManager.GetString("ULSView_Decentralize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULS Name already exists..
        /// </summary>
        public static string ULSVM_ULSNameExists {
            get {
                return ResourceManager.GetString("ULSVM_ULSNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULS Name is required..
        /// </summary>
        public static string ULSVM_ULSNameNotEmpty {
            get {
                return ResourceManager.GetString("ULSVM_ULSNameNotEmpty", resourceCulture);
            }
        }
    }
}
