//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS.Presentation.KMT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesOfR5 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesOfR5() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIS.Presentation.KMT.Properties.ResourcesOfR5", typeof(ResourcesOfR5).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To :.
        /// </summary>
        public static string Common_ColumnAssignedTo {
            get {
                return ResourceManager.GetString("Common_ColumnAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack. Received Date.
        /// </summary>
        public static string Common_ColumnHeaderAckFileDate {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderAckFileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Report Unique ID.
        /// </summary>
        public static string Common_ColumnHeaderCustomerReportUniqueID {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderCustomerReportUniqueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Common_ColumnHeaderDescription {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfillment Number.
        /// </summary>
        public static string Common_ColumnHeaderFulfillmentNumber {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderFulfillmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Encrypted.
        /// </summary>
        public static string Common_ColumnHeaderIsEncrypted {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderIsEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Export.
        /// </summary>
        public static string Common_ColumnHeaderIsExport {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderIsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Maximum.
        /// </summary>
        public static string Common_ColumnHeaderKeysMaximum {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderKeysMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Minimum.
        /// </summary>
        public static string Common_ColumnHeaderKeysMinimum {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderKeysMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensable Part Number.
        /// </summary>
        public static string Common_ColumnHeaderLicensablePartNumber {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderLicensablePartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated date.
        /// </summary>
        public static string Common_ColumnHeaderModifiedDate {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Fulfulled Date.
        /// </summary>
        public static string Common_ColumnHeaderMSFulfulledDate {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderMSFulfulledDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Report Unique ID.
        /// </summary>
        public static string Common_ColumnHeaderMSReportUniqueID {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderMSReportUniqueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Status.
        /// </summary>
        public static string Common_ColumnHeaderNewState {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderNewState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Status.
        /// </summary>
        public static string Common_ColumnHeaderOldState {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderOldState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Unique ID.
        /// </summary>
        public static string Common_ColumnHeaderOrderUniqueId {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderOrderUniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Days.
        /// </summary>
        public static string Common_ColumnHeaderOverDays {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderOverDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship To.
        /// </summary>
        public static string Common_ColumnHeaderShipTo {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold To.
        /// </summary>
        public static string Common_ColumnHeaderSoldTo {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderSoldTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target .
        /// </summary>
        public static string Common_ColumnHeaderTarget {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To.
        /// </summary>
        public static string Common_ColumnoAssignTo {
            get {
                return ResourceManager.GetString("Common_ColumnoAssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory :.
        /// </summary>
        public static string Common_Directory {
            get {
                return ResourceManager.GetString("Common_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t popup.
        /// </summary>
        public static string Common_DontPopupAgain {
            get {
                return ResourceManager.GetString("Common_DontPopupAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        public static string Common_EncryptedDisplay {
            get {
                return ResourceManager.GetString("Common_EncryptedDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Date From :.
        /// </summary>
        public static string Common_ExportDateFrom {
            get {
                return ResourceManager.GetString("Common_ExportDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To :.
        /// </summary>
        public static string Common_ExportTo {
            get {
                return ResourceManager.GetString("Common_ExportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed Keys :.
        /// </summary>
        public static string Common_failedKeys {
            get {
                return ResourceManager.GetString("Common_failedKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed type :.
        /// </summary>
        public static string Common_FailedType {
            get {
                return ResourceManager.GetString("Common_FailedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name :.
        /// </summary>
        public static string Common_FileName {
            get {
                return ResourceManager.GetString("Common_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path :.
        /// </summary>
        public static string Common_FilePath {
            get {
                return ResourceManager.GetString("Common_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Common_Info {
            get {
                return ResourceManager.GetString("Common_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensable Part Number :.
        /// </summary>
        public static string Common_LicensablePartNumber {
            get {
                return ResourceManager.GetString("Common_LicensablePartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Fulfilled Date :.
        /// </summary>
        public static string Common_MSFulfilledDate {
            get {
                return ResourceManager.GetString("Common_MSFulfilledDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Common_Notifications {
            get {
                return ResourceManager.GetString("Common_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM Optional Info.
        /// </summary>
        public static string Common_OEMOptionInfo {
            get {
                return ResourceManager.GetString("Common_OEMOptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity don&apos;t allow more than 5000 keys one time..
        /// </summary>
        public static string Common_OperationLimitQualityMsg {
            get {
                return ResourceManager.GetString("Common_OperationLimitQualityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No keys to operate..
        /// </summary>
        public static string Common_OperationNoKeysMsg {
            get {
                return ResourceManager.GetString("Common_OperationNoKeysMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subsidiary to operate..
        /// </summary>
        public static string Common_OperationNoSubsidiaryMsg {
            get {
                return ResourceManager.GetString("Common_OperationNoSubsidiaryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input quantity can&apos;t be greater than available quantity..
        /// </summary>
        public static string Common_OperationQuantityOver {
            get {
                return ResourceManager.GetString("Common_OperationQuantityOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Key ID :.
        /// </summary>
        public static string Common_ProductKeyID {
            get {
                return ResourceManager.GetString("Common_ProductKeyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string Common_ProxySetting {
            get {
                return ResourceManager.GetString("Common_ProxySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a directory.
        /// </summary>
        public static string Common_SelectDirectory {
            get {
                return ResourceManager.GetString("Common_SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include over 72 hours.
        /// </summary>
        public static string Common_ShowAll {
            get {
                return ResourceManager.GetString("Common_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful keys :.
        /// </summary>
        public static string Common_succeedKeys {
            get {
                return ResourceManager.GetString("Common_succeedKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Info :.
        /// </summary>
        public static string Common_TrackingInfo {
            get {
                return ResourceManager.GetString("Common_TrackingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnEncrypted.
        /// </summary>
        public static string Common_UnEncryptedDisplay {
            get {
                return ResourceManager.GetString("Common_UnEncryptedDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Common_View {
            get {
                return ResourceManager.GetString("Common_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Common_ViewDetail {
            get {
                return ResourceManager.GetString("Common_ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test internal web service.
        /// </summary>
        public static string Diagnostic_InternalConnection {
            get {
                return ResourceManager.GetString("Diagnostic_InternalConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Microsoft web service.
        /// </summary>
        public static string Diagnostic_MicrosoftConnection {
            get {
                return ResourceManager.GetString("Diagnostic_MicrosoftConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection to Up Level System.
        /// </summary>
        public static string Diagnostic_ULSConnection {
            get {
                return ResourceManager.GetString("Diagnostic_ULSConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Relationship ID :.
        /// </summary>
        public static string EditOptionalInfo_ChaRelId {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ChaRelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Relationship ID.
        /// </summary>
        public static string EditOptionalInfo_ColumnHeaderChaRelId {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ColumnHeaderChaRelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture GeoLocation.
        /// </summary>
        public static string EditOptionalInfo_ColumnHeaderManGeo {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ColumnHeaderManGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM Extended Identifier.
        /// </summary>
        public static string EditOptionalInfo_ColumnHeaderOemExtId {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ColumnHeaderOemExtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Model/SKU Number.
        /// </summary>
        public static string EditOptionalInfo_ColumnHeaderPcModelSku {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ColumnHeaderPcModelSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Eligibility Values.
        /// </summary>
        public static string EditOptionalInfo_ColumnHeaderProEligValue {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ColumnHeaderProEligValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture GeoLocation :.
        /// </summary>
        public static string EditOptionalInfo_ManGeo {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ManGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM Extended Identifier :.
        /// </summary>
        public static string EditOptionalInfo_OemExtId {
            get {
                return ResourceManager.GetString("EditOptionalInfo_OemExtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Model/SKU Number :.
        /// </summary>
        public static string EditOptionalInfo_PcModelSku {
            get {
                return ResourceManager.GetString("EditOptionalInfo_PcModelSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Eligibility Values :.
        /// </summary>
        public static string EditOptionalInfo_ProEligValue {
            get {
                return ResourceManager.GetString("EditOptionalInfo_ProEligValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Optional Information.
        /// </summary>
        public static string EditOptionalInfo_Title {
            get {
                return ResourceManager.GetString("EditOptionalInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Model/SKU&apos;s length is too long. .
        /// </summary>
        public static string EditOptionalInfoViewModel_PcModelSkuError {
            get {
                return ResourceManager.GetString("EditOptionalInfoViewModel_PcModelSkuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Eligibility Values&apos;s length is too long..
        /// </summary>
        public static string EditOptionalInfoViewModel_ProEligValueError {
            get {
                return ResourceManager.GetString("EditOptionalInfoViewModel_ProEligValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Oem Optional Information :  {1} successful, {0} failed ..
        /// </summary>
        public static string EditOptionalInfoViewModel_UpdateResult {
            get {
                return ResourceManager.GetString("EditOptionalInfoViewModel_UpdateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CBR to MS.
        /// </summary>
        public static string Export_CBRTxt {
            get {
                return ResourceManager.GetString("Export_CBRTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Keys to {0}.
        /// </summary>
        public static string Export_ConfirmToMsg {
            get {
                return ResourceManager.GetString("Export_ConfirmToMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Duplicate CBR.
        /// </summary>
        public static string Export_DuplicateCBRTxt {
            get {
                return ResourceManager.GetString("Export_DuplicateCBRTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name or path..
        /// </summary>
        public static string Export_InvalidPath {
            get {
                return ResourceManager.GetString("Export_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Keys to Down Level System (FKI/FFKI).
        /// </summary>
        public static string Export_KeysTxt {
            get {
                return ResourceManager.GetString("Export_KeysTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Keys to Down Level System (FFKI).
        /// </summary>
        public static string Export_KeysTxtTpi {
            get {
                return ResourceManager.GetString("Export_KeysTxtTpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        public static string Export_Ms {
            get {
                return ResourceManager.GetString("Export_Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Only encrypted file can be re-exported..
        /// </summary>
        public static string Export_Note {
            get {
                return ResourceManager.GetString("Export_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Export CBR to MS.
        /// </summary>
        public static string Export_ReCBRTxt {
            get {
                return ResourceManager.GetString("Export_ReCBRTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Export Duplicated CBR.
        /// </summary>
        public static string Export_ReDuplicateCBRTxt {
            get {
                return ResourceManager.GetString("Export_ReDuplicateCBRTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Export Keys to Down Level System (FKI/FFKI).
        /// </summary>
        public static string Export_ReKeysTxt {
            get {
                return ResourceManager.GetString("Export_ReKeysTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Export Keys to Down Level System (FFKI).
        /// </summary>
        public static string Export_ReKeysTxtTpi {
            get {
                return ResourceManager.GetString("Export_ReKeysTxtTpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Keys to Up Level System (CKI/FKI).
        /// </summary>
        public static string Export_ReportKeysTxt {
            get {
                return ResourceManager.GetString("Export_ReportKeysTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Keys to Up Level System (CKI).
        /// </summary>
        public static string Export_ReportKeysTxtTpi {
            get {
                return ResourceManager.GetString("Export_ReportKeysTxtTpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Export Keys to Up Level System (CKI/FKI).
        /// </summary>
        public static string Export_ReReportKeysTxt {
            get {
                return ResourceManager.GetString("Export_ReReportKeysTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Export Keys to Up Level System (CKI).
        /// </summary>
        public static string Export_ReReportKeysTxtTpi {
            get {
                return ResourceManager.GetString("Export_ReReportKeysTxtTpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported Keys : {0} successful,  {1} failed.
        /// </summary>
        public static string Export_resultMsg {
            get {
                return ResourceManager.GetString("Export_resultMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Export Keys to OA3Tool.
        /// </summary>
        public static string Export_ReToolKeysTxt {
            get {
                return ResourceManager.GetString("Export_ReToolKeysTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Duplicated CBR.
        /// </summary>
        public static string Export_SelectDuplicateKeyTit {
            get {
                return ResourceManager.GetString("Export_SelectDuplicateKeyTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an encrypted file..
        /// </summary>
        public static string Export_SelectEncryptedLogMsg {
            get {
                return ResourceManager.GetString("Export_SelectEncryptedLogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select  file..
        /// </summary>
        public static string Export_SelectLogMsg {
            get {
                return ResourceManager.GetString("Export_SelectLogMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string Export_SelectLogTit {
            get {
                return ResourceManager.GetString("Export_SelectLogTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Keys to OA3Tool.
        /// </summary>
        public static string Export_ToolKeysTxt {
            get {
                return ResourceManager.GetString("Export_ToolKeysTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Keys Details.
        /// </summary>
        public static string Export_ViewKeyTit {
            get {
                return ResourceManager.GetString("Export_ViewKeyTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Keys.
        /// </summary>
        public static string Export_WinTit {
            get {
                return ResourceManager.GetString("Export_WinTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Duplicated CBR key(s).
        /// </summary>
        public static string ExportDuplicateCBRNotificationViewModel_DuplicateCBRsMessage {
            get {
                return ResourceManager.GetString("ExportDuplicateCBRNotificationViewModel_DuplicateCBRsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include exported CBR.
        /// </summary>
        public static string ExportDuplicateCBRNotificationViewModel_ExportCBRAgain {
            get {
                return ResourceManager.GetString("ExportDuplicateCBRNotificationViewModel_ExportCBRAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Duplicated CBR Key(s).
        /// </summary>
        public static string ExportDuplicateCBRNotificationViewModel_ViewTitle {
            get {
                return ResourceManager.GetString("ExportDuplicateCBRNotificationViewModel_ViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ExportKey_ConfirmMsg {
            get {
                return ResourceManager.GetString("ExportKey_ConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt File.
        /// </summary>
        public static string ExportKey_Encryptselect {
            get {
                return ResourceManager.GetString("ExportKey_Encryptselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting file without encryption will result in high security risk.
        /// </summary>
        public static string ExportKey_NonEncryptMsg {
            get {
                return ResourceManager.GetString("ExportKey_NonEncryptMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CBR ACK. from MS.
        /// </summary>
        public static string Import_CBRAckTxt {
            get {
                return ResourceManager.GetString("Import_CBRAckTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Duplicated CBR.
        /// </summary>
        public static string Import_DuplicateCBRTxt {
            get {
                return ResourceManager.GetString("Import_DuplicateCBRTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Keys from Up Level System (CKI/FKI).
        /// </summary>
        public static string Import_KeysTxt {
            get {
                return ResourceManager.GetString("Import_KeysTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Keys from Up Level System (CKI).
        /// </summary>
        public static string Import_KeysTxtTpi {
            get {
                return ResourceManager.GetString("Import_KeysTxtTpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Keys from Down Level System (FKI/FFKI).
        /// </summary>
        public static string Import_ReportKeysTxt {
            get {
                return ResourceManager.GetString("Import_ReportKeysTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Keys from Down Level System (FFKI).
        /// </summary>
        public static string Import_ReportKeysTxtTpi {
            get {
                return ResourceManager.GetString("Import_ReportKeysTxtTpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string Import_SelectFileTit {
            get {
                return ResourceManager.GetString("Import_SelectFileTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Keys from OA3Tool.
        /// </summary>
        public static string Import_ToolkeysTxt {
            get {
                return ResourceManager.GetString("Import_ToolkeysTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Keys.
        /// </summary>
        public static string Import_WinTit {
            get {
                return ResourceManager.GetString("Import_WinTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported Keys :  {0} successful,  {1} failed.
        /// </summary>
        public static string ImportKey_ResultMsg {
            get {
                return ResourceManager.GetString("ImportKey_ResultMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} key(s) exceed time line.
        /// </summary>
        public static string KeyManagementViewModel_OldTimelineExceedMessage {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_OldTimelineExceedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Line Days : {0} day(s)..
        /// </summary>
        public static string KeysExpiredNotificationViewModel_TimeLineDays {
            get {
                return ResourceManager.GetString("KeysExpiredNotificationViewModel_TimeLineDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum :.
        /// </summary>
        public static string KeysStockConfigView_KeysMaximum {
            get {
                return ResourceManager.GetString("KeysStockConfigView_KeysMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum :.
        /// </summary>
        public static string KeysStockConfigView_KeysMinimum {
            get {
                return ResourceManager.GetString("KeysStockConfigView_KeysMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensable Part Number Stock.
        /// </summary>
        public static string KeysStockConfigView_Title {
            get {
                return ResourceManager.GetString("KeysStockConfigView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected any MS Part Number ..
        /// </summary>
        public static string KeysStockConfigViewModel_MsPartNumberNotSelect {
            get {
                return ResourceManager.GetString("KeysStockConfigViewModel_MsPartNumberNotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum must be greater than Minimum..
        /// </summary>
        public static string KeysStockConfigViewModel_RangeError {
            get {
                return ResourceManager.GetString("KeysStockConfigViewModel_RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Licensable Part Number(s) stock.
        /// </summary>
        public static string KeysStockNotificationView_Title {
            get {
                return ResourceManager.GetString("KeysStockNotificationView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Time Line Exceed Keys.
        /// </summary>
        public static string MainWindow_KeysExpired {
            get {
                return ResourceManager.GetString("MainWindow_KeysExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Acknowledgement.
        /// </summary>
        public static string MainWindow_ReAcknowledgement {
            get {
                return ResourceManager.GetString("MainWindow_ReAcknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Fulfillment.
        /// </summary>
        public static string MainWindow_ReFulfillment {
            get {
                return ResourceManager.GetString("MainWindow_ReFulfillment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string MainWindow_Return {
            get {
                return ResourceManager.GetString("MainWindow_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents have been copied to clipboard..
        /// </summary>
        public static string Notification_CopiedToClipboard {
            get {
                return ResourceManager.GetString("Notification_CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Licensable Part Number(s) stock are out of range..
        /// </summary>
        public static string Notification_KeysStockOutOfRangeMessage {
            get {
                return ResourceManager.GetString("Notification_KeysStockOutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} acknowledgement(s) failed..
        /// </summary>
        public static string Notification_ReAcknowledgeMessage {
            get {
                return ResourceManager.GetString("Notification_ReAcknowledgeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} fulfillment(s) failed..
        /// </summary>
        public static string Notification_ReFulfillmentMessage {
            get {
                return ResourceManager.GetString("Notification_ReFulfillmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications ({0}).
        /// </summary>
        public static string Notification_YouHaveNotifications {
            get {
                return ResourceManager.GetString("Notification_YouHaveNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBR.
        /// </summary>
        public static string Offline_CBRTit {
            get {
                return ResourceManager.GetString("Offline_CBRTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLS.
        /// </summary>
        public static string Offline_DLSTit {
            get {
                return ResourceManager.GetString("Offline_DLSTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate CBR.
        /// </summary>
        public static string Offline_DuplicateCBRTit {
            get {
                return ResourceManager.GetString("Offline_DuplicateCBRTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OA3Tool.
        /// </summary>
        public static string Offline_OA3ToolTit {
            get {
                return ResourceManager.GetString("Offline_OA3ToolTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULS.
        /// </summary>
        public static string Offline_ULSTit {
            get {
                return ResourceManager.GetString("Offline_ULSTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string ProxySetting_Customize {
            get {
                return ResourceManager.GetString("ProxySetting_Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use IE Proxy Setting.
        /// </summary>
        public static string ProxySetting_Default {
            get {
                return ResourceManager.GetString("ProxySetting_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ProxySetting_None {
            get {
                return ResourceManager.GetString("ProxySetting_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL.
        /// </summary>
        public static string ProxySetting_UseSSL {
            get {
                return ResourceManager.GetString("ProxySetting_UseSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason  must  between 0 and 200 characters..
        /// </summary>
        public static string Revert_MsgLength {
            get {
                return ResourceManager.GetString("Revert_MsgLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Reason.
        /// </summary>
        public static string Revert_ReasonPageTit {
            get {
                return ResourceManager.GetString("Revert_ReasonPageTit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert Keys :  {0} successful,  {1} failed.
        /// </summary>
        public static string Revert_ResultMsg {
            get {
                return ResourceManager.GetString("Revert_ResultMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert Keys.
        /// </summary>
        public static string Revert_RevertTxt {
            get {
                return ResourceManager.GetString("Revert_RevertTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert Reason :.
        /// </summary>
        public static string RevertKey_ReasonTxt {
            get {
                return ResourceManager.GetString("RevertKey_ReasonTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Keys :.
        /// </summary>
        public static string RevertKey_SelectedTxt {
            get {
                return ResourceManager.GetString("RevertKey_SelectedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Level System Customer Number must not be equal to  current Customer Number..
        /// </summary>
        public static string SSIDEditorViewModel_SSIDCNNotBeCN {
            get {
                return ResourceManager.GetString("SSIDEditorViewModel_SSIDCNNotBeCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use your ULS customer number as yours..
        /// </summary>
        public static string SystemSettingView_CustomerNumberShouldNotInHeadQuarter {
            get {
                return ResourceManager.GetString("SystemSettingView_CustomerNumberShouldNotInHeadQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Carbon Copy.
        /// </summary>
        public static string SystemSettingView_IsCarbonCopy {
            get {
                return ResourceManager.GetString("SystemSettingView_IsCarbonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Certificate Subject is required..
        /// </summary>
        public static string SystemSettingView_MSCertNotEmpty {
            get {
                return ResourceManager.GetString("SystemSettingView_MSCertNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Level System Customer Number must not be equal to  current Customer Number..
        /// </summary>
        public static string ULSSettingViewModel_ULSCNNotBeCN {
            get {
                return ResourceManager.GetString("ULSSettingViewModel_ULSCNNotBeCN", resourceCulture);
            }
        }
    }
}
