//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS.Presentation.KMT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ThirdResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThirdResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIS.Presentation.KMT.Properties.ThirdResources", typeof(ThirdResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access path is denied!.
        /// </summary>
        public static string AccessFileDenied {
            get {
                return ResourceManager.GetString("AccessFileDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned keys:  {0} successful, {1}  failed.
        /// </summary>
        public static string AssignKeysViewModel_AssignKeysResult {
            get {
                return ResourceManager.GetString("AssignKeysViewModel_AssignKeysResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key(s) state have been changed, please refresh this page..
        /// </summary>
        public static string AssignKeysViewModel_KeyStateNotValid {
            get {
                return ResourceManager.GetString("AssignKeysViewModel_KeyStateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack File Date.
        /// </summary>
        public static string Common_ColumnHeaderAckFileDate {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderAckFileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Failed.
        /// </summary>
        public static string Common_ColumnHeaderIsFailed {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderIsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Common_ColumnHeaderName {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Result.
        /// </summary>
        public static string Common_ColumnHeaderOperationResult {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderOperationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Processing.
        /// </summary>
        public static string Common_ColumnHeaderProcessing {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship To.
        /// </summary>
        public static string Common_ColumnHeaderShipTo {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold To.
        /// </summary>
        public static string Common_ColumnHeaderSoldTo {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderSoldTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Fulfilled Date.
        /// </summary>
        public static string Common_ColumnMSFulfilledDate {
            get {
                return ResourceManager.GetString("Common_ColumnMSFulfilledDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Common_FailedTxt {
            get {
                return ResourceManager.GetString("Common_FailedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait....
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string Common_SuccessfulTxt {
            get {
                return ResourceManager.GetString("Common_SuccessfulTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Timeline must be between {0} and {1} days..
        /// </summary>
        public static string Configuration_InvalidLifeDays {
            get {
                return ResourceManager.GetString("Configuration_InvalidLifeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Down Level System ?.
        /// </summary>
        public static string ConfirmationRemoveDLS {
            get {
                return ResourceManager.GetString("ConfirmationRemoveDLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart KMT to apply language change!.
        /// </summary>
        public static string CreateUserViewModel_ApplyLanguageChange {
            get {
                return ResourceManager.GetString("CreateUserViewModel_ApplyLanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required!.
        /// </summary>
        public static string CreateUserViewModel_PasswordRequired {
            get {
                return ResourceManager.GetString("CreateUserViewModel_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity don&apos;t allow more than 5000 keys one time..
        /// </summary>
        public static string ExportKey_LimitQualityMsg {
            get {
                return ResourceManager.GetString("ExportKey_LimitQualityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Data has changed,please reselect keys!.
        /// </summary>
        public static string ExportKeys_DataChangeError {
            get {
                return ResourceManager.GetString("ExportKeys_DataChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-export Keys for OA3Tool/CBR.
        /// </summary>
        public static string ExportKeysViewModel_ReExport_FFK {
            get {
                return ResourceManager.GetString("ExportKeysViewModel_ReExport_FFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-export Keys.
        /// </summary>
        public static string ExportKeysViewModel_ReExport_OEM {
            get {
                return ResourceManager.GetString("ExportKeysViewModel_ReExport_OEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-export Keys/CBR.
        /// </summary>
        public static string ExportKeysViewModel_ReExport_TPI {
            get {
                return ResourceManager.GetString("ExportKeysViewModel_ReExport_TPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string GridPaging_Page {
            get {
                return ResourceManager.GetString("GridPaging_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Per Page.
        /// </summary>
        public static string GridPaging_RowsPerPage {
            get {
                return ResourceManager.GetString("GridPaging_RowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Keys :.
        /// </summary>
        public static string GridPaging_TotalKeys {
            get {
                return ResourceManager.GetString("GridPaging_TotalKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Keys.
        /// </summary>
        public static string ImportKey_RbKeytxt_FFK {
            get {
                return ResourceManager.GetString("ImportKey_RbKeytxt_FFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CBR.
        /// </summary>
        public static string ImportKey_RbKeytxt_OEM {
            get {
                return ResourceManager.GetString("ImportKey_RbKeytxt_OEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Keys/CBR.
        /// </summary>
        public static string ImportKey_RbKeytxt_TPI {
            get {
                return ResourceManager.GetString("ImportKey_RbKeytxt_TPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import details:.
        /// </summary>
        public static string ImportKeysViewModel_ImportDetails {
            get {
                return ResourceManager.GetString("ImportKeysViewModel_ImportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Duplicate CBR.
        /// </summary>
        public static string ImportKeysViewModel_ImportDuplicateCBRTxt {
            get {
                return ResourceManager.GetString("ImportKeysViewModel_ImportDuplicateCBRTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key List.
        /// </summary>
        public static string KeyManagementView_KeyList {
            get {
                return ResourceManager.GetString("KeyManagementView_KeyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} duplicated CBR key(s).
        /// </summary>
        public static string KeyManagementViewModel_DuplicateCBRsMessage {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_DuplicateCBRsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft web service is disabled. Please configure Microsoft subject name in Options to enable it. .
        /// </summary>
        public static string KeyManagementViewModel_FulfillmentDisableMsService {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_FulfillmentDisableMsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfilled key from Microsoft failed!.
        /// </summary>
        public static string KeyManagementViewModel_FulfillmentFail {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_FulfillmentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key available from Microsoft!.
        /// </summary>
        public static string KeyManagementViewModel_FulfillmentNoKeys {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_FulfillmentNoKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfilled {0} key(s) from Microsoft successful!.
        /// </summary>
        public static string KeyManagementViewModel_FulfillmentSucc {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_FulfillmentSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-Level-System service is not available!.
        /// </summary>
        public static string KeyManagementViewModel_GetKeyNoHeadQuarter {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_GetKeyNoHeadQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get key from {0} failed!.
        /// </summary>
        public static string KeyManagementViewModel_GetKeysFail {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_GetKeysFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key available from {0}!.
        /// </summary>
        public static string KeyManagementViewModel_GetKeysNoKeys {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_GetKeysNoKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0} key(s) from {1} successful!.
        /// </summary>
        public static string KeyManagementViewModel_GetKeysSucc {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_GetKeysSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string KeyManager_DisplayNo {
            get {
                return ResourceManager.GetString("KeyManager_DisplayNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string KeyManager_DisplayYes {
            get {
                return ResourceManager.GetString("KeyManager_DisplayYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of export file is not supported..
        /// </summary>
        public static string KeyProxy_CBRExportFormatNotSupported {
            get {
                return ResourceManager.GetString("KeyProxy_CBRExportFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of import file is not supported..
        /// </summary>
        public static string KeyProxy_CBRImportFormatNotSupported {
            get {
                return ResourceManager.GetString("KeyProxy_CBRImportFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Log.
        /// </summary>
        public static string MainWindow_OperationLog {
            get {
                return ResourceManager.GetString("MainWindow_OperationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Log.
        /// </summary>
        public static string MainWindow_SystemLog {
            get {
                return ResourceManager.GetString("MainWindow_SystemLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalled keys:  {0} successful, {1}  failed.
        /// </summary>
        public static string RecallKeysViewModel_RecallKeysResult {
            get {
                return ResourceManager.GetString("RecallKeysViewModel_RecallKeysResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported keys:  {0} successful, {1}  failed.
        /// </summary>
        public static string ReportKeysViewModel_ReportSuccess {
            get {
                return ResourceManager.GetString("ReportKeysViewModel_ReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid keys to revert!.
        /// </summary>
        public static string RevertKeys_Nokeys {
            get {
                return ResourceManager.GetString("RevertKeys_Nokeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason of Revert key(s).
        /// </summary>
        public static string RevertKeys_RevertReason {
            get {
                return ResourceManager.GetString("RevertKeys_RevertReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected of revert key(s).
        /// </summary>
        public static string RevertKeys_RevertSelectMsg {
            get {
                return ResourceManager.GetString("RevertKeys_RevertSelectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} key(s) are reverted..
        /// </summary>
        public static string RevertKeys_RevertSummary {
            get {
                return ResourceManager.GetString("RevertKeys_RevertSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Certificate Subject :.
        /// </summary>
        public static string SystemSettingView_CertificateSubject {
            get {
                return ResourceManager.GetString("SystemSettingView_CertificateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulfillment Interval(minute(s)) :.
        /// </summary>
        public static string SystemSettingView_FulfillmentInterval {
            get {
                return ResourceManager.GetString("SystemSettingView_FulfillmentInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Timeline(day(s)) :.
        /// </summary>
        public static string SystemSettingView_OldTimeline {
            get {
                return ResourceManager.GetString("SystemSettingView_OldTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Interval(minute(s)) :.
        /// </summary>
        public static string SystemSettingView_ReportInterval {
            get {
                return ResourceManager.GetString("SystemSettingView_ReportInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart KMT to apply Customer Number change!.
        /// </summary>
        public static string SystemSettingViewModel_ApplyCustomerNumber {
            get {
                return ResourceManager.GetString("SystemSettingViewModel_ApplyCustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned keys:  {0} successful,  {1}  failed.
        /// </summary>
        public static string UnassignKeysViewModel_UnassignKeysResult {
            get {
                return ResourceManager.GetString("UnassignKeysViewModel_UnassignKeysResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is duplicated!.
        /// </summary>
        public static string UpLevelSystemViewModel_CustomNameDuplicate {
            get {
                return ResourceManager.GetString("UpLevelSystemViewModel_CustomNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required!.
        /// </summary>
        public static string UpLevelSystemViewModel_CustomNameNotEmpty {
            get {
                return ResourceManager.GetString("UpLevelSystemViewModel_CustomNameNotEmpty", resourceCulture);
            }
        }
    }
}
