//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS.Presentation.KMT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ThirdResources_pr_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThirdResources_pr_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIS.Presentation.KMT.Properties.ThirdResources.pr-BR", typeof(ThirdResources_pr_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access path is denied!.
        /// </summary>
        public static string AccessFileDenied {
            get {
                return ResourceManager.GetString("AccessFileDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaves atribuídas:  {0} com êxito, {1} com falha.
        /// </summary>
        public static string AssignKeysViewModel_AssignKeysResult {
            get {
                return ResourceManager.GetString("AssignKeysViewModel_AssignKeysResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado da(s) chave(s) foi alterado, atualize esta página..
        /// </summary>
        public static string AssignKeysViewModel_KeyStateNotValid {
            get {
                return ResourceManager.GetString("AssignKeysViewModel_KeyStateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinês Simplificado (简体中文).
        /// </summary>
        public static string Common_Chinese {
            get {
                return ResourceManager.GetString("Common_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do Arquivo Ack.
        /// </summary>
        public static string Common_ColumnHeaderAckFileDate {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderAckFileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com Falha.
        /// </summary>
        public static string Common_ColumnHeaderIsFailed {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderIsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Common_ColumnHeaderName {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado da Operação.
        /// </summary>
        public static string Common_ColumnHeaderOperationResult {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderOperationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Processing.
        /// </summary>
        public static string Common_ColumnHeaderProcessing {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remeter para.
        /// </summary>
        public static string Common_ColumnHeaderShipTo {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendido para.
        /// </summary>
        public static string Common_ColumnHeaderSoldTo {
            get {
                return ResourceManager.GetString("Common_ColumnHeaderSoldTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Fornecimento (MS).
        /// </summary>
        public static string Common_ColumnMSFulfilledDate {
            get {
                return ResourceManager.GetString("Common_ColumnMSFulfilledDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha.
        /// </summary>
        public static string Common_FailedTxt {
            get {
                return ResourceManager.GetString("Common_FailedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japonês (日本語).
        /// </summary>
        public static string Common_Japanese {
            get {
                return ResourceManager.GetString("Common_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando, aguarde....
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome:.
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português (Português).
        /// </summary>
        public static string Common_Portuguese {
            get {
                return ResourceManager.GetString("Common_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com Êxito.
        /// </summary>
        public static string Common_SuccessfulTxt {
            get {
                return ResourceManager.GetString("Common_SuccessfulTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinês Tradicional (繁体中文).
        /// </summary>
        public static string Common_Taiwan {
            get {
                return ResourceManager.GetString("Common_Taiwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Timeline must be between {0} and {1} days..
        /// </summary>
        public static string Configuration_InvalidLifeDays {
            get {
                return ResourceManager.GetString("Configuration_InvalidLifeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Down Level System ?.
        /// </summary>
        public static string ConfirmationRemoveDLS {
            get {
                return ResourceManager.GetString("ConfirmationRemoveDLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinicie a KMT para aplicar a alteração de idioma..
        /// </summary>
        public static string CreateUserViewModel_ApplyLanguageChange {
            get {
                return ResourceManager.GetString("CreateUserViewModel_ApplyLanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é necessária..
        /// </summary>
        public static string CreateUserViewModel_PasswordRequired {
            get {
                return ResourceManager.GetString("CreateUserViewModel_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade não permite mais que 5000 chaves de uma vez..
        /// </summary>
        public static string ExportKey_LimitQualityMsg {
            get {
                return ResourceManager.GetString("ExportKey_LimitQualityMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do banco de dados alterados. Selecione as chaves novamente..
        /// </summary>
        public static string ExportKeys_DataChangeError {
            get {
                return ResourceManager.GetString("ExportKeys_DataChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do banco de dados alterados. Selecione as chaves novamente..
        /// </summary>
        public static string ExportKeysViewModel_ReExport_FFK {
            get {
                return ResourceManager.GetString("ExportKeysViewModel_ReExport_FFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reexportar Chaves.
        /// </summary>
        public static string ExportKeysViewModel_ReExport_OEM {
            get {
                return ResourceManager.GetString("ExportKeysViewModel_ReExport_OEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-export Keys/CBR.
        /// </summary>
        public static string ExportKeysViewModel_ReExport_TPI {
            get {
                return ResourceManager.GetString("ExportKeysViewModel_ReExport_TPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        public static string GridPaging_Page {
            get {
                return ResourceManager.GetString("GridPaging_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linhas por Página.
        /// </summary>
        public static string GridPaging_RowsPerPage {
            get {
                return ResourceManager.GetString("GridPaging_RowsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de Chaves:.
        /// </summary>
        public static string GridPaging_TotalKeys {
            get {
                return ResourceManager.GetString("GridPaging_TotalKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linhas por Página.
        /// </summary>
        public static string ImportKey_RbKeytxt_FFK {
            get {
                return ResourceManager.GetString("ImportKey_RbKeytxt_FFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar CBR.
        /// </summary>
        public static string ImportKey_RbKeytxt_OEM {
            get {
                return ResourceManager.GetString("ImportKey_RbKeytxt_OEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar Chaves/CBR.
        /// </summary>
        public static string ImportKey_RbKeytxt_TPI {
            get {
                return ResourceManager.GetString("ImportKey_RbKeytxt_TPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da importação:.
        /// </summary>
        public static string ImportKeysViewModel_ImportDetails {
            get {
                return ResourceManager.GetString("ImportKeysViewModel_ImportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar CBR Duplicado.
        /// </summary>
        public static string ImportKeysViewModel_ImportDuplicateCBRTxt {
            get {
                return ResourceManager.GetString("ImportKeysViewModel_ImportDuplicateCBRTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Chaves.
        /// </summary>
        public static string KeyManagementView_KeyList {
            get {
                return ResourceManager.GetString("KeyManagementView_KeyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você possui {0} chave(s) de CBR duplicada(s).
        /// </summary>
        public static string KeyManagementViewModel_DuplicateCBRsMessage {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_DuplicateCBRsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O serviço Web da Microsoft está desativado. Configure o nome da entidade da Microsoft em Opções para ativá-la..
        /// </summary>
        public static string KeyManagementViewModel_FulfillmentDisableMsService {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_FulfillmentDisableMsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao obter Chave Fulfilled da Microsoft..
        /// </summary>
        public static string KeyManagementViewModel_FulfillmentFail {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_FulfillmentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma chave disponível da Microsoft..
        /// </summary>
        public static string KeyManagementViewModel_FulfillmentNoKeys {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_FulfillmentNoKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êxito ao obter {0} chave(s) Fulfilled da Microsoft..
        /// </summary>
        public static string KeyManagementViewModel_FulfillmentSucc {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_FulfillmentSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O serviço do Sistema Up-Level não está disponível..
        /// </summary>
        public static string KeyManagementViewModel_GetKeyNoHeadQuarter {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_GetKeyNoHeadQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha em obter chave de {0}..
        /// </summary>
        public static string KeyManagementViewModel_GetKeysFail {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_GetKeysFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma chave disponível de {0}..
        /// </summary>
        public static string KeyManagementViewModel_GetKeysNoKeys {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_GetKeysNoKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êxito ao obter {0} chave(s) de {1}..
        /// </summary>
        public static string KeyManagementViewModel_GetKeysSucc {
            get {
                return ResourceManager.GetString("KeyManagementViewModel_GetKeysSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to não.
        /// </summary>
        public static string KeyManager_DisplayNo {
            get {
                return ResourceManager.GetString("KeyManager_DisplayNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sim.
        /// </summary>
        public static string KeyManager_DisplayYes {
            get {
                return ResourceManager.GetString("KeyManager_DisplayYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato do arquivo de exportação sem suporte..
        /// </summary>
        public static string KeyProxy_CBRExportFormatNotSupported {
            get {
                return ResourceManager.GetString("KeyProxy_CBRExportFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato do arquivo de importação sem suporte..
        /// </summary>
        public static string KeyProxy_CBRImportFormatNotSupported {
            get {
                return ResourceManager.GetString("KeyProxy_CBRImportFormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log de Operação.
        /// </summary>
        public static string MainWindow_OperationLog {
            get {
                return ResourceManager.GetString("MainWindow_OperationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log do Sistema.
        /// </summary>
        public static string MainWindow_SystemLog {
            get {
                return ResourceManager.GetString("MainWindow_SystemLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaves canceladas:  {0} com êxito, {1} com falha.
        /// </summary>
        public static string RecallKeysViewModel_RecallKeysResult {
            get {
                return ResourceManager.GetString("RecallKeysViewModel_RecallKeysResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaves relatadas:  {0} com êxito, {1} com falha.
        /// </summary>
        public static string ReportKeysViewModel_ReportSuccess {
            get {
                return ResourceManager.GetString("ReportKeysViewModel_ReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma chave válida a ser revertida..
        /// </summary>
        public static string RevertKeys_Nokeys {
            get {
                return ResourceManager.GetString("RevertKeys_Nokeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O motivo de Reverter chave(s).
        /// </summary>
        public static string RevertKeys_RevertReason {
            get {
                return ResourceManager.GetString("RevertKeys_RevertReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seleção de Reverter chave(s).
        /// </summary>
        public static string RevertKeys_RevertSelectMsg {
            get {
                return ResourceManager.GetString("RevertKeys_RevertSelectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chave(s) serão revertidas..
        /// </summary>
        public static string RevertKeys_RevertSummary {
            get {
                return ResourceManager.GetString("RevertKeys_RevertSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade do Certificado Microsoft:.
        /// </summary>
        public static string SystemSettingView_CertificateSubject {
            get {
                return ResourceManager.GetString("SystemSettingView_CertificateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalo de Fornecimento (minutos(s)):.
        /// </summary>
        public static string SystemSettingView_FulfillmentInterval {
            get {
                return ResourceManager.GetString("SystemSettingView_FulfillmentInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linha de tempo antiga (dia(s)):.
        /// </summary>
        public static string SystemSettingView_OldTimeline {
            get {
                return ResourceManager.GetString("SystemSettingView_OldTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalo de Relatório (minutos(s)):.
        /// </summary>
        public static string SystemSettingView_ReportInterval {
            get {
                return ResourceManager.GetString("SystemSettingView_ReportInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinicie a KMT para aplicar a alteração de Número do Cliente..
        /// </summary>
        public static string SystemSettingViewModel_ApplyCustomerNumber {
            get {
                return ResourceManager.GetString("SystemSettingViewModel_ApplyCustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaves desatribuídas:  {0} com êxito, {1} com falha.
        /// </summary>
        public static string UnassignKeysViewModel_UnassignKeysResult {
            get {
                return ResourceManager.GetString("UnassignKeysViewModel_UnassignKeysResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome duplicado..
        /// </summary>
        public static string UpLevelSystemViewModel_CustomNameDuplicate {
            get {
                return ResourceManager.GetString("UpLevelSystemViewModel_CustomNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome necessário..
        /// </summary>
        public static string UpLevelSystemViewModel_CustomNameNotEmpty {
            get {
                return ResourceManager.GetString("UpLevelSystemViewModel_CustomNameNotEmpty", resourceCulture);
            }
        }
    }
}
