//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace Platform.DAAS.OData.Security.Extension
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yale.edu/tp/cas")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.yale.edu/tp/cas", IsNullable = false, ElementName = "serviceResponse")]
    public partial class ServiceResponse
    {

        private ServiceResponseAuthenticationSuccess[] successItemsField;

        private ServiceResponseAuthenticationFailure[] failureItemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("authenticationSuccess")]
        public ServiceResponseAuthenticationSuccess[] SuccessItems
        {
            get
            {
                return this.successItemsField;
            }
            set
            {
                this.successItemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("authenticationFailure", IsNullable = true)]
        public ServiceResponseAuthenticationFailure[] FailureItems
        {
            get
            {
                return this.failureItemsField;
            }
            set
            {
                this.failureItemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yale.edu/tp/cas")]
    [XmlRoot(ElementName = "serviceResponseAuthenticationSuccess")]
    public partial class ServiceResponseAuthenticationSuccess
    {
        private string userField;
        [XmlElement(ElementName = "user")]
        /// <remarks/>
        public string User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        [XmlElement("attributes")]
        public ServiceResponseAuthenticationSuccessAttributes Attributes
        {
            get;set;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yale.edu/tp/cas")]
    [XmlRoot(ElementName = "serviceResponseAuthenticationSuccessAttributes")]
    public partial class ServiceResponseAuthenticationSuccessAttributes
    {

        private string phoneField;

        private string nickNameField;

        private string emailField;

        private string userTypeField;

        private string userIdField;

        /// <remarks/>
        /// 
        [XmlElement(ElementName = "phone")]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        /// 
        [XmlElement(ElementName = "nickName")]
        public string NickName
        {
            get
            {
                return this.nickNameField;
            }
            set
            {
                this.nickNameField = value;
            }
        }

        /// <remarks/>
        /// 
        [XmlElement(ElementName = "email")]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        /// 
        [XmlElement(ElementName = "userType")]
        public string UserType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }

        /// <remarks/>
        /// 
        [XmlElement(ElementName = "userId")]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.yale.edu/tp/cas")]
    [XmlRoot(ElementName = "serviceResponseAuthenticationFailure")]
    public partial class ServiceResponseAuthenticationFailure
    {

        private string codeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "code")]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}