// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
//using Newtonsoft.Json;
//using Newtonsoft.Json.Linq;
using System.Runtime.Serialization;

namespace Platform.DAAS.OData.Security.Extension
{ 
    [DataContract]
    public class CasUserInfo
    {
        //[JsonProperty("userId")]
        [DataMember(Name = "userId")]
        public string UserId { get; set; }

        [DataMember(Name = "userName")]
        public string UserName { get; set; }

        //[JsonProperty("userType")]
        [DataMember(Name = "userType")]
        public string UserType { get; set; }

        //[JsonProperty("nickName")]
        [DataMember(Name = "nickName")]
        public string NickName { get; set; }

        //[JsonProperty("phone")]
        [DataMember(Name = "phone")]
        public string Phone { get; set; }

        //[JsonProperty("email")]
        [DataMember(Name = "email")]
        public string Email { get; set; }
    }
}
