//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.summaryunassignedkeys
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class items { }
#else

	public class items : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public items()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/DIS;component/SampleData/summaryunassignedkeys/summaryunassignedkeys.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private itemCollection _itemCollection = new itemCollection();

		public itemCollection itemCollection
		{
			get
			{
				return this._itemCollection;
			}
		}
	}

	public class item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private double _productkeyid = 0;

		public double productkeyid
		{
			get
			{
				return this._productkeyid;
			}

			set
			{
				if (this._productkeyid != value)
				{
					this._productkeyid = value;
					this.OnPropertyChanged("productkeyid");
				}
			}
		}

		private string _productkey = string.Empty;

		public string productkey
		{
			get
			{
				return this._productkey;
			}

			set
			{
				if (this._productkey != value)
				{
					this._productkey = value;
					this.OnPropertyChanged("productkey");
				}
			}
		}

		private string _keystatus = string.Empty;

		public string keystatus
		{
			get
			{
				return this._keystatus;
			}

			set
			{
				if (this._keystatus != value)
				{
					this._keystatus = value;
					this.OnPropertyChanged("keystatus");
				}
			}
		}

		private string _mspartnumber = string.Empty;

		public string mspartnumber
		{
			get
			{
				return this._mspartnumber;
			}

			set
			{
				if (this._mspartnumber != value)
				{
					this._mspartnumber = value;
					this.OnPropertyChanged("mspartnumber");
				}
			}
		}

		private string _oempartnumber = string.Empty;

		public string oempartnumber
		{
			get
			{
				return this._oempartnumber;
			}

			set
			{
				if (this._oempartnumber != value)
				{
					this._oempartnumber = value;
					this.OnPropertyChanged("oempartnumber");
				}
			}
		}
	}

	public class itemCollection : System.Collections.ObjectModel.ObservableCollection<item>
	{ 
	}
#endif
}
