ALTER TABLE [dbo].[ComputerBuildReport]
    ADD CONSTRAINT [PK_ComputerBuildReport] PRIMARY KEY CLUSTERED ([CustomerReportUniqueID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

