ALTER TABLE [dbo].[ComputerBuildReportKey]
    ADD CONSTRAINT [PK_ComputerBuildReportKey] PRIMARY KEY CLUSTERED ([CustomerReportUniqueID] ASC, [ProductKeyID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

