ALTER TABLE [dbo].[DuplicatedKey]
    ADD CONSTRAINT [PK_DuplicatedKey] PRIMARY KEY CLUSTERED ([DuplicatedKeyID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

