ALTER TABLE [dbo].[DuplicatedComputerBuildReport]
    ADD CONSTRAINT [PK_DuplicatedComputerBuildReport] PRIMARY KEY CLUSTERED ([CustomerReportUniqueID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

