ALTER TABLE [dbo].[HeadQuarter]
    ADD CONSTRAINT [PK_HeadQuarter] PRIMARY KEY CLUSTERED ([HeadQuarterID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

