ALTER TABLE [dbo].[KeyExportLog]
    ADD CONSTRAINT [PK_KeyExportLog] PRIMARY KEY CLUSTERED ([ExportLogID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

