/*ALTER TABLE [dbo].[KeySyncNotification]
    ADD CONSTRAINT [PK_SyncNotification] PRIMARY KEY CLUSTERED ([SyncID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

