ALTER TABLE [dbo].[Subsidiary]
    ADD CONSTRAINT [PK_Subsidiary] PRIMARY KEY CLUSTERED ([SSID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

