ALTER TABLE [dbo].[UserRole]
	ADD CONSTRAINT [PK_UserRole] PRIMARY KEY CLUSTERED ([UserID] ASC,
	[RoleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
