////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated from a template.
////
////     Manual changes to this file may cause unexpected behavior in your application.
////     Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace KnowledgeCenter.Security
//{
//    using System;
//    using System.Data.Entity;
//    using System.Data.Entity.Infrastructure;

//    public partial class AuthEntityModelContainer : DbContext
//    {
//        public AuthEntityModelContainer()
//            : base("name=AuthEntityModelContainer")
//        {
//        }

//        protected override void OnModelCreating(DbModelBuilder modelBuilder)
//        {
//            throw new UnintentionalCodeFirstException();
//        }

//        public virtual DbSet<Operation> Operations { get; set; }
//        public virtual DbSet<DataScope> DataScopes { get; set; }
//        public virtual DbSet<ObjectOperationAuthItem> ObjectOperationAuthItems { get; set; }
//        public virtual DbSet<RoleOperation> RoleOperations { get; set; }
//        public virtual DbSet<RoleDataScope> RoleDataScopes { get; set; }
//    }
//}
