//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false, ElementName = "resources")]
public partial class ResourceAuthConfiguration {
    
    private Resource[] resourceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("resource")]
    //[XmlArray(ElementName = "resource")]
    //[System.Xml.Serialization.XmlArrayItemAttribute("resource", IsNullable = false)]
    public Resource[] Resources {
        get {
            return this.resourceField;
        }
        set {
            this.resourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=false)]
public partial class Resource {
    
    private Subject[] subjectsField;
    
    private Scope[] scopesField;
    
    private Action[] actionsField;
    
    private string idField;
    
    private string nameField;

    private string keyField;
    
    [XmlArray(ElementName ="subjects")]
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("subject", IsNullable=false)]
    public Subject[] Subjects {
        get {
            return this.subjectsField;
        }
        set {
            this.subjectsField = value;
        }
    }

    [XmlArray(ElementName = "scopes")]
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("scope", IsNullable=false)]
    public Scope[] Scopes {
        get {
            return this.scopesField;
        }
        set {
            this.scopesField = value;
        }
    }

    [XmlArray(ElementName = "actions")]
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("action", IsNullable=false)]
    public Action[] Actions {
        get {
            return this.actionsField;
        }
        set {
            this.actionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttribute(AttributeName = "id")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "name")]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }

    [XmlElement(ElementName = "key")]
    public string Key
    {
        get { return this.keyField; }
        set { this.keyField = value; }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=false)]
public partial class Subject {
    
    private string idField;
    
    private string nameField;
    
    private string typeField;

    private string descriptionField;
    
    [XmlElement(ElementName ="id")]
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    [XmlElement(ElementName = "name")]
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "type")]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [XmlElement(ElementName = "description")]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=false)]
public partial class Scope {
    
    private string idField;
    
    private string nameField;
    
    private string typeField;
    
    [XmlElement(ElementName = "id")]
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    [XmlElement(ElementName = "name")]
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    [XmlElement(ElementName = "type")]
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=false)]
public partial class Action {
    
    private string idField;
    
    private string nameField;
    
    [XmlElement(ElementName ="id")]
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }

    [XmlElement(ElementName = "name")]
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}
