//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string ButtonText_Skip {
            get {
                return ResourceManager.GetString("ButtonText_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the wizard below to create a new configuration set.
        /// </summary>
        internal static string Desc_NewCustomer {
            get {
                return ResourceManager.GetString("Desc_NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business ID.
        /// </summary>
        internal static string Label_BusinessID {
            get {
                return ResourceManager.GetString("Label_BusinessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        internal static string Label_BusinessName {
            get {
                return ResourceManager.GetString("Label_BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Type.
        /// </summary>
        internal static string Legend_ConfigurationType {
            get {
                return ResourceManager.GetString("Legend_ConfigurationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Connection.
        /// </summary>
        internal static string Legend_DatabaseConnection {
            get {
                return ResourceManager.GetString("Legend_DatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Connection String.
        /// </summary>
        internal static string Legend_DatabaseConnectionString {
            get {
                return ResourceManager.GetString("Legend_DatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Level System Database.
        /// </summary>
        internal static string Legend_DownLevelSystemDatabase {
            get {
                return ResourceManager.GetString("Legend_DownLevelSystemDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Legend_Summary {
            get {
                return ResourceManager.GetString("Legend_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Level System Database.
        /// </summary>
        internal static string Legend_UpLevelSystemDatabase {
            get {
                return ResourceManager.GetString("Legend_UpLevelSystemDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Information.
        /// </summary>
        internal static string Legened_BusinessInformation {
            get {
                return ResourceManager.GetString("Legened_BusinessInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Configuration Set.
        /// </summary>
        internal static string Title_NewCustomer {
            get {
                return ResourceManager.GetString("Title_NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Business Information.
        /// </summary>
        internal static string Title_WizardStep1 {
            get {
                return ResourceManager.GetString("Title_WizardStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Up Level System Database.
        /// </summary>
        internal static string Title_WizardStep2 {
            get {
                return ResourceManager.GetString("Title_WizardStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Down Level System Database.
        /// </summary>
        internal static string Title_WizardStep3 {
            get {
                return ResourceManager.GetString("Title_WizardStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4: Conformation.
        /// </summary>
        internal static string Title_WizardStep4 {
            get {
                return ResourceManager.GetString("Title_WizardStep4", resourceCulture);
            }
        }
    }
}
