//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.keyselect
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class keys { }
#else

	public class keys : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public keys()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/DIS;component/SampleData/keyselect/keyselect.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private keyCollection _keyCollection = new keyCollection();

		public keyCollection keyCollection
		{
			get
			{
				return this._keyCollection;
			}
		}
	}

	public class key : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _mslicensablenumber = string.Empty;

		public string mslicensablenumber
		{
			get
			{
				return this._mslicensablenumber;
			}

			set
			{
				if (this._mslicensablenumber != value)
				{
					this._mslicensablenumber = value;
					this.OnPropertyChanged("mslicensablenumber");
				}
			}
		}

		private string _oempartnumber = string.Empty;

		public string oempartnumber
		{
			get
			{
				return this._oempartnumber;
			}

			set
			{
				if (this._oempartnumber != value)
				{
					this._oempartnumber = value;
					this.OnPropertyChanged("oempartnumber");
				}
			}
		}

		private string _description = string.Empty;

		public string description
		{
			get
			{
				return this._description;
			}

			set
			{
				if (this._description != value)
				{
					this._description = value;
					this.OnPropertyChanged("description");
				}
			}
		}

		private double _available = 0;

		public double available
		{
			get
			{
				return this._available;
			}

			set
			{
				if (this._available != value)
				{
					this._available = value;
					this.OnPropertyChanged("available");
				}
			}
		}

		private double _exportquantity = 0;

		public double exportquantity
		{
			get
			{
				return this._exportquantity;
			}

			set
			{
				if (this._exportquantity != value)
				{
					this._exportquantity = value;
					this.OnPropertyChanged("exportquantity");
				}
			}
		}
	}

	public class keyCollection : System.Collections.ObjectModel.ObservableCollection<key>
	{ 
	}
#endif
}
