//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace DISAdapter
{

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    //public partial class OA3 {

    //    //private object[] itemsField;

    //    ///// <remarks/>
    //    //[System.Xml.Serialization.XmlElementAttribute("FileBased", typeof(OA3FileBased), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    //[System.Xml.Serialization.XmlElementAttribute("OutputData", typeof(OA3OutputData), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    //public object[] Items {
    //    //    get {
    //    //        return this.itemsField;
    //    //    }
    //    //    set {
    //    //        this.itemsField = value;
    //    //    }
    //    //}
    //}

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class OA3FileBased : OA3ToolConfiguration
    {
        private string inputKeyXMLFileField;

        private string parametersField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InputKeyXMLFile
        {
            get
            {
                return this.inputKeyXMLFileField;
            }
            set
            {
                this.inputKeyXMLFileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
}