//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.Users
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class Users { }
#else

	public class Users : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public Users()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/DIS;component/SampleData/Users/Users.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private UserCollection _UserCollection = new UserCollection();

		public UserCollection UserCollection
		{
			get
			{
				return this._UserCollection;
			}
		}
	}

	public class User : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _name = string.Empty;

		public string name
		{
			get
			{
				return this._name;
			}

			set
			{
				if (this._name != value)
				{
					this._name = value;
					this.OnPropertyChanged("name");
				}
			}
		}

		private string _alias = string.Empty;

		public string alias
		{
			get
			{
				return this._alias;
			}

			set
			{
				if (this._alias != value)
				{
					this._alias = value;
					this.OnPropertyChanged("alias");
				}
			}
		}

		private string _roles = string.Empty;

		public string roles
		{
			get
			{
				return this._roles;
			}

			set
			{
				if (this._roles != value)
				{
					this._roles = value;
					this.OnPropertyChanged("roles");
				}
			}
		}

		private string _addeddate = string.Empty;

		public string addeddate
		{
			get
			{
				return this._addeddate;
			}

			set
			{
				if (this._addeddate != value)
				{
					this._addeddate = value;
					this.OnPropertyChanged("addeddate");
				}
			}
		}

		private string _firstname = string.Empty;

		public string firstname
		{
			get
			{
				return this._firstname;
			}

			set
			{
				if (this._firstname != value)
				{
					this._firstname = value;
					this.OnPropertyChanged("firstname");
				}
			}
		}

		private string _secondname = string.Empty;

		public string secondname
		{
			get
			{
				return this._secondname;
			}

			set
			{
				if (this._secondname != value)
				{
					this._secondname = value;
					this.OnPropertyChanged("secondname");
				}
			}
		}

		private string _email = string.Empty;

		public string email
		{
			get
			{
				return this._email;
			}

			set
			{
				if (this._email != value)
				{
					this._email = value;
					this.OnPropertyChanged("email");
				}
			}
		}

		private string _thumbnail = string.Empty;

		public string thumbnail
		{
			get
			{
				return this._thumbnail;
			}

			set
			{
				if (this._thumbnail != value)
				{
					this._thumbnail = value;
					this.OnPropertyChanged("thumbnail");
				}
			}
		}

		private double _phone = 0;

		public double phone
		{
			get
			{
				return this._phone;
			}

			set
			{
				if (this._phone != value)
				{
					this._phone = value;
					this.OnPropertyChanged("phone");
				}
			}
		}

		private string _department = string.Empty;

		public string department
		{
			get
			{
				return this._department;
			}

			set
			{
				if (this._department != value)
				{
					this._department = value;
					this.OnPropertyChanged("department");
				}
			}
		}
	}

	public class UserCollection : System.Collections.ObjectModel.ObservableCollection<User>
	{ 
	}
#endif
}
