//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;

namespace DataIntegrator
{
    public class Adapter : IAdapter
    {
        public virtual EndPoint Source
        {
            get;
            set;
        }

        public virtual EndPoint Destination
        {
            get;
            set;
        }

        public virtual EndPoint Transformer
        {
            get;
            set;
        }

        public virtual object Adapt(object Parameter)
        {
            object[] results = this.Source.Connect(null, null);

            results = this.Transformer.Connect(null, results[0]);

            results = this.Destination.Connect(null, results[0]);

            return results;
        }

        public virtual object Compare(object Parameter)
        {
            throw new System.NotImplementedException();
        }
    }
}