//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataIntegrator
{
    public class Argument
    {
        public virtual String Name
        {
            get;
            set;
        }

        public virtual String Value
        {
            get;
            set;
        }

        public virtual String Category
        {
            get; 
            set; 
        }
    }
}

