//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataIntegrator
{
    public abstract class EndPoint : IEndPoint
    {
        public virtual Protocol Protocol
        {
            get;
            set;
        }

        public virtual string DataType
        {
            get;
            set;
        }

        public virtual Authentication Authentication
        {
            get;
            set;
        }

        public virtual List<Operation> Operations
        {
            get;
            set;
        }

        public virtual string Address
        {
            get;
            set;
        }

        public virtual object[] Connect(params object[] Parameters)
        {
            throw new System.NotImplementedException();
        }

        public virtual Operation GetOperation(int Index) 
        {
            if ((this.Operations != null) && (this.Operations.Count > 0))
            {
                if ((Index >= 0) && (Index < this.Operations.Count))
                {
                    return this.Operations[Index];
                }
            }

            return null;
        }

        public virtual Operation GetOperation(string OperationName)
        {
            if ((this.Operations != null) && (this.Operations.Count > 0) && (!String.IsNullOrEmpty(OperationName)))
            {
                foreach (Operation operation in this.Operations)
                {
                    if ((operation.Name != null) && (operation.Name.ToLower() == OperationName.ToLower()))
                    {
                        return operation;
                    }
                }
            }

            return null;
        }

        public virtual Operation GetOperation(OperationMethod OperationMethod) 
        {
            if ((this.Operations != null) && (this.Operations.Count > 0))
            {
                foreach (Operation operation in this.Operations)
                {
                    if (operation.Method == OperationMethod)
                    {
                        return operation;
                    }
                }
            }

            return null;
        }
    }
}

