//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataIntegrator
{
    public enum OperationMethod
    {
        Create = 0,
        Modify = 1,
        Replace = 2,
        Append = 3,
        Delete = 4,
        Move = 5,
        Retrieve = 6,
        List = 7,
        BatchWrite = 8
    }
}
