//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Adapter : IAdapter
{
	public virtual EndPoint Source
	{
		get;
		set;
	}

	public virtual EndPoint Destination
	{
		get;
		set;
	}

	public virtual EndPoint Transformer
	{
		get;
		set;
	}

	public virtual uint Adapt(uint Parameter)
	{
		throw new System.NotImplementedException();
	}

	public virtual uint Compare(uint Parameter)
	{
		throw new System.NotImplementedException();
	}

}

