//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public enum AuthenticationType
{
	PlainText = 0,
	X509Certificate = 1,
	Kerberos = 2,
	NTLM = 3,
	Negociate = 4,
}
