//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class EndPoint : IEndPoint
{
	public virtual Protocol Protocol
	{
		get;
		set;
	}

	public virtual string DataType
	{
		get;
		set;
	}

	public virtual Authentication Authentication
	{
		get;
		set;
	}

	public virtual IEnumerable<Operation> Operations
	{
		get;
		set;
	}

	public virtual string Address
	{
		get;
		set;
	}

	public virtual uint Connect(uint Parameter)
	{
		throw new System.NotImplementedException();
	}

}

