//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Operation
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual string Message
	{
		get;
		set;
	}

	public virtual OperationMethod Method
	{
		get;
		set;
	}

	public virtual IEnumerable<Argument> Arguments
	{
		get;
		set;
	}

	public virtual string GetArgumentValue(string ArgumentName)
	{
		throw new System.NotImplementedException();
	}

}

