//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public enum OperationMethod
{
	HttpGet = 0,
	HttpPost = 1,
	HttpPut = 2,
	HttpDelete = 3,
	Insert = 5,
	Update = 6,
	Delete = 7,
	Select = 4,
	Create = 9,
	Modify = 10,
	Replace = 12,
	Append = 11,
	Remove = 13,
	List = 8,
}
