// stdafx.h : include file for standard system include files,
// or project specific include files that are used frequently, but
// are changed infrequently
//

#pragma once

#include "targetver.h"

#define WIN32_LEAN_AND_MEAN             // Exclude rarely-used stuff from Windows headers
// Windows Header Files:
#include <windows.h>

// TODO: reference additional headers your program requires here
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <tchar.h>
#include <string>

#include "kplistener.h" // header file generated by the MIDL compiler
#include "string.h"
#include "resources.h"
#include "UnmanagedRpc.h"